### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by GavinSong123** [kubernetes/dashboard#1093]
Versions of Node.js, Go etc. are needed only from developers. To get them use console:

Dashboard version: latest
Operating system: ubuntu 16.04
Node.js version: v6.3.1
Go version: 1.6.2

gulp build

 [11:36:39] Requiring external module babel-register
/home/ennew/gowork/dashboard/gulpfile.babel.js:21
import './build/check';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at loader (/home/ennew/gowork/dashboard/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ennew/gowork/dashboard/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)

**Comment by maciaszczykm** [comment]
Did you run `npm install` successfully? 

Please check following docs, perhaps you have missed some steps:
- https://github.com/kubernetes/dashboard/blob/master/docs/devel/requirements-installation.md
- https://github.com/kubernetes/dashboard/blob/master/docs/devel/getting-started.md
