### ISSUE TITLE
Null pointer exception when getting workload

### ISSUE THREAD

**Issue by achew22** [kubernetes/dashboard#1124]
##### Environment
```
Dashboard version: 1.1
Kubernetes version: 1.3.0
Operating system: CoreOS
Node.js version: N/A (installed via docker images)
Go version: N/A (installed via docker images)
```

##### Steps to reproduce
Install kubernetes-dashboard in my cluster by running `kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml`

Note host and port in this message:

```
deployment "kubernetes-dashboard" created
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:31797) to serve traffic.

See http://releases.k8s.io/release-1.2/docs/user-guide/services-firewalls.md for more details.
```

Since this is a single node deploy, I know the host.

Navigate to `http://host:port`

kubernetes-dashboard makes a request to `http://host:port/api/v1/workload?itemsPerPage=10&page=1`
kubernetes-dashboard crashes with this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x67f5bb]

goroutine 91 [running]:
panic(0x13f6a00, 0xc420014020)
        /usr/lib/google-golang/src/runtime/panic.go:502 +0x1b3
github.com/kubernetes/dashboard/src/app/backend/resource/job.CreateJobList(0xc42061cc00, 0x4, 0x4, 0xc420353200, 0x10, 0x10, 0xc42038a000, 0x18, 0x21, 0xc42047a350, ...)
        /usr/local/google/home/bryk/src/github.com/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/job/joblist.go:111 +0x27b
github.com/kubernetes/dashboard/src/app/backend/resource/job.GetJobListFromChannels(0xc42010ec30, 0xc42047a350, 0x0, 0x0, 0x0)
        /usr/local/google/home/bryk/src/github.com/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/job/joblist.go:93 +0x445
github.com/kubernetes/dashboard/src/app/backend/resource/workload.GetWorkloadsFromChannels.func3(0xc42010ec30, 0xc42047a350, 0xc42020d4a0, 0xc42020d260)
        /usr/local/google/home/bryk/src/github.com/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/workload/workloads.go:97 +0x39
created by github.com/kubernetes/dashboard/src/app/backend/resource/workload.GetWorkloadsFromChannels
        /usr/local/google/home/bryk/src/github.com/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/resource/workload/workloads.go:100 +0x22f
```

##### Observed result
Server crashes

##### Expected result
Server returns list of workloads

**Comment by bryk** [comment]
This is already fixed by https://github.com/kubernetes/dashboard/pull/1113. 

Try to use latest `:canary` version in your YAML file. Or wait till 1.1.2 version is released.

**Comment by julia-allyce** [comment]
Any word on when 1.1.2 will be pushed out?

**Comment by bryk** [comment]
We already have 1.4.0-beta2 released. Check it out at: https://github.com/kubernetes/dashboard/releases
