### ISSUE TITLE
Prerequisite checks in gulp scripts

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#113]
Many people fail to run Dashboard because Godep is not in path. The error message is not obvious to non-nodejs developer. Please improve the error message.

@taimir can you take over

**Comment by cheld** [comment]
Unit recently, when executing gulp serve:prod another non-obvious error can occur in case environment variables are not passed to root. However, in latest version we do check GOPATH variable and the execution will exit. So, a user will most likely realize his wrong action. Anyway, in case it is simple, please add another check:


cheld@estheld:~/devel/dashboard$ sudo env "GOPATH=$GOPATH" gulp serve:prod
[09:08:27] Requiring external module babel-core/register
[09:08:29] Using gulpfile ~/devel/dashboard/gulpfile.babel.js
[09:08:29] Starting 'assets'...
[09:08:29] Starting 'angular-templates'...
[09:08:29] Starting 'styles:prod'...
[09:08:29] Starting 'package-backend-source'...
[09:08:29] Starting 'kill-backend'...
[09:08:29] Finished 'kill-backend' after 47 μs
[09:08:29] Finished 'assets' after 103 ms
[09:08:29] Finished 'styles:prod' after 126 ms
[09:08:29] Finished 'package-backend-source' after 131 ms
[09:08:29] Starting 'backend:prod'...
execvp(): No such file or directory

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)


However,

**Comment by bryk** [comment]
Yes, this would be extremely helpful. Most people don't realize they need godep for a frontend project.

Another idea that struck me is that we could stop requiring godep and download it during a build step, e.g., 

```
go get godep
$GOPATH/bin/godep go <commad> 
```

This could actually work.

**Comment by taimir** [comment]
I am on it first thing tomorrow morning :) (Moving in to my new apartment right now)

**Comment by taimir** [comment]
+1 at @bryk, the download is usually quite fast

**Comment by cheld** [comment]
Please consider 'go clean', because it might remove godep again. This might be non-intentional.

**Comment by cheld** [comment]
Fixed. Environment variables are checked. In addition godep is downloaded by npm and does not require user setup any longer
