### ISSUE TITLE
fail building dashboard

### ISSUE THREAD

**Issue by roflmao** [kubernetes/dashboard#115]
Golang 1.5.1
NodeJS 4.2.2

```
~/git/dashboard] master 5s 1 ± gulp build
[13:59:38] Requiring external module babel-core/register
[13:59:41] Using gulpfile ~/git/dashboard/gulpfile.babel.js
[13:59:41] Starting 'package-backend-source'...
[13:59:41] Starting 'assets'...
[13:59:41] Starting 'angular-templates'...
[13:59:41] Starting 'styles:prod'...
[13:59:41] Finished 'assets' after 158 ms
[13:59:41] Finished 'styles:prod' after 216 ms
[13:59:41] Finished 'package-backend-source' after 275 ms
[13:59:41] Starting 'backend:prod'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn godep ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by bryk** [comment]
Need to install Godep and add it to `$PATH`.

Btw., we're fixing the error message to make it human readable. 

@cheld

**Comment by roflmao** [comment]
Success! Thanks

This did the trick:
```
go get github.com/tools/godep
export PATH=$PATH:$GOPATH/bin
```

**Comment by cheld** [comment]
Please note, if you run go clean, than godep is gone. I would rather copy the binary to some other place like /usr/local/bin ...

**Comment by bryk** [comment]
Yeah, that's why I think moving godep download to a build step would benefit all of us.
