### ISSUE TITLE
on master can't docker run successfully

### ISSUE THREAD

**Issue by xiaoping378** [kubernetes/dashboard#1252]
#### Issue details
on the latest master, and docker images is also the latest.
##### Steps to reproduce

``` docker run -ti --rm -v "$PWD":/k8sdocs -p 4000:4000 johndmulhausen/k8sdocs```

##### Expected result
```
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find minitest-5.9.0 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/spec_set.rb:88:in `map!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/spec_set.rb:88:in `materialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/definition.rb:140:in `specs'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/definition.rb:185:in `specs_for'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/definition.rb:174:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/environment.rb:19:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/runtime.rb:14:in `setup'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler.rb:95:in `setup'
	from /usr/local/bundle/gems/jekyll-3.1.6/lib/jekyll/plugin_manager.rb:33:in `require_from_bundler'
	from /usr/local/bundle/gems/jekyll-3.1.6/bin/jekyll:9:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:22:in `load'
	from /usr/local/bundle/bin/jekyll:22:in `<main>'
```

**Comment by colemickens** [comment]
Is this filed in the right place? This looks like an issue for kubernetes/kubernetes.github.io repo maybe?

cc: @johndmulhausen (because of the container name)

**Comment by xiaoping378** [comment]
o.... sorry.
