### ISSUE TITLE
Can't build docker image

### ISSUE THREAD

**Issue by johanhaleby** [kubernetes/dashboard#181]
I'm trying to build the docker image but it fails:

```bash
$ npm install gulp
....
$ gulp docker-image
[08:23:10] Failed to load external module babel-core/register
[08:23:10] Failed to load external module babel/register
/Users/xxx/k8s-dashboard/gulpfile.babel.js:21
import './build/check';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
```

**Comment by johanhaleby** [comment]
Sorry rookie mistake, I forgot to run `npm install`. Please ignore the issue.
