### ISSUE TITLE
Failed to load external module babel-register

### ISSUE THREAD

**Issue by mrzkhd** [kubernetes/dashboard#2506]
##### Environment
I wanna run kubernetes locally to try dashboard. So after installing requirements, I did clone repo and after that run `npm -install`
when installation is done I ran gulp command and encounter and error.

`command: gulp local-up-cluster --heapsterServerHost 'http://localhost:8082'
`
```
Dashboard version:
Kubernetes version:
Operating system: macOS Sierra 
Node.js version:v4.4.7
Go version: go version go1.9.1 darwin/amd64
```

##### Observed result

```
[13:49:59] Failed to load external module babel-register
[13:49:59] Requiring external module babel-core/register
/Users/Mohammadreza/Development/Projects/cloud/dashboard/build/check.js:86
function getLicenseFileFilter(...ext) {
                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/Users/Mohammadreza/Development/Projects/cloud/dashboard/node_modules/babel-core/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Mohammadreza/Development/Projects/cloud/dashboard/node_modules/babel-core/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Mohammadreza/Development/Projects/cloud/dashboard/gulpfile.babel.js:21:1)
    at Module._compile (module.js:409:26)


##### 
I tried step by step from Getting started page for Development Guide.

**Comment by floreks** [comment]
Take a look at required dependencies versions: https://github.com/kubernetes/dashboard/wiki/Getting-started#preparation

**Comment by maciaszczykm** [comment]
`local-up-cluster` no longer exists.

**Comment by mrzkhd** [comment]
after double checking dependencies, I got new issue :

```
[16:34:58] Requiring external module babel-register
[16:35:02] Using gulpfile ~/Development/Projects/cloud/dashboard/gulpfile.babel.js
[16:35:02] Task 'local-up-cluster' is not in your gulpfile
[16:35:02] Please check the documentation for proper gulpfile formatting

```

**Comment by maciaszczykm** [comment]
@mrzkhd Did you read what we said?
