### ISSUE TITLE
run-gulp-in-docker.sh seemingly fails to install dependency

### ISSUE THREAD

**Issue by robrsprd** [kubernetes/dashboard#2511]
Fellow Dashboard-Team,

me and my team very appreciate the functionality introduced in the 1.7.x release as we just started to give people granular permissions via RBAC and needed a way to reflect those in the dashboard. Now its there, which is great, but i noticed an annoying detail in functionality as people will often run into 403 when trying to access resources they are not allowed to. In this case the menu toggles invisible (for no obvious reason to me, maybe you can reevaluate this behavour - but thats another story) and has to be toggled visible again. So I decided to change a line of code and rebuild the project. As I dont do any web development at all, I decided to use the gulp_in_docker script to keep my environment clean, but it unfortunately ran into an error. repeatedly. So I installed the needed tools and ran it on my local mashine again, and it worked. I can perfectly live with that, but i believe you guys would like to know if there is something wrong :)
##### Environment

```
Dashboard version: 1.7.1
Kubernetes version:1.6.11
Docker version: 17.06.2-ce
```

##### Steps to reproduce
clone repo
checkout tag 1.7.1
run ./run-gulp-in-docker.sh docker-image:head

##### Observed result
```
[09:29:15] Starting 'index:prod'...
{ Error: rauchg/ms.js is not installed. Try running `bower install` or remove the component from your bower.json file.
    at /dashboard/node_modules/wiredep/lib/detect-dependencies.js:147:19
    at /dashboard/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/dashboard/node_modules/lodash/lodash.js:3001:24)
    at /dashboard/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/dashboard/node_modules/lodash/lodash.js:9359:14)
    at /dashboard/node_modules/wiredep/lib/detect-dependencies.js:183:11
    at /dashboard/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/dashboard/node_modules/lodash/lodash.js:3001:24)
    at /dashboard/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/dashboard/node_modules/lodash/lodash.js:9359:14)
    at /dashboard/node_modules/wiredep/lib/detect-dependencies.js:183:11
    at /dashboard/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/dashboard/node_modules/lodash/lodash.js:3001:24)
    at /dashboard/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/dashboard/node_modules/lodash/lodash.js:9359:14)
    at detectDependencies (/dashboard/node_modules/wiredep/lib/detect-dependencies.js:34:7)
    at wiredep (/dashboard/node_modules/wiredep/wiredep.js:70:39)
    at DestroyableTransform._transform (/dashboard/node_modules/wiredep/wiredep.js:136:34)
    at DestroyableTransform.Transform._read (/dashboard/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/dashboard/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/dashboard/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/dashboard/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/dashboard/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at DestroyableTransform.ondata (/dashboard/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at addChunk (/dashboard/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/dashboard/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at DestroyableTransform.Readable.push (/dashboard/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at DestroyableTransform.Transform.push (/dashboard/node_modules/readable-stream/lib/_stream_transform.js:146:32)
    at DestroyableTransform.<anonymous> (/dashboard/node_modules/gulp-inject/src/inject/index.js:88:12)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 code: 'PKG_NOT_INSTALLED' }
[09:29:15] Finished 'index:prod' after 93 ms
```

##### Expected result
No missing dependencies!

**Comment by maciaszczykm** [comment]
@robrsprd Following error looks strange considering we have moved away from Bower as a dependency manager recently:

`Try running `bower install` or remove the component from your bower.json file`

I think we have to verify if the script works because we are not using it on a daily basis. You may also want to verify if you are using latest configuration, codebase etc.

Thank you for reporting this.

**Comment by cheld** [comment]
For the time being you might want to install the required tools locally. Takes only a 5 minutes:
https://github.com/kubernetes/dashboard/wiki/Getting-started

**Comment by floreks** [comment]
Did you run `npm i` again after checking out tag?

**Comment by tkeech1** [comment]
Hello, 
I saw the same error and was able to fix it by modifying the Dockerfile:

- Changed base image to golang:1.8.5-stretch
- Updated nodejs to version 8
- Added "apt-get install patch"
- Changed  order of RUN commands so "npm install --unsafe-perm" runs after the source tree is copied into the image

I'm new to this project so let me know if this sounds like a good solution. Thanks.

**Comment by maciaszczykm** [comment]
@tkeech1 Hi, your fix works fine. The main thing that was missing was `patch` package. Updating Node.js to the newer version is also a good idea. Thanks!
