### ISSUE TITLE
run backend test fail

### ISSUE THREAD

**Issue by chunnallu** [kubernetes/dashboard#2546]
##### Environment

```
Dashboard version:  1.6.3
Kubernetes version: 1.5.5
Operating system: Ubuntu 16.04.3 LTS
Node.js version:  v6.11.4
Go version:  go1.8.3 linux/amd64
```

##### Steps to reproduce

1. install kubernetes 1.5.5 and heapster

2. install dashboard 1.6.3 on the same server

3. set environments

```
export KUBERNETES_SERVICE_HOST=191.8.2.184
export KUBERNETES_SERVICE_PORT=8080
```

4. run `gulp backend-test` and report the error

##### Observed result

When running `gulp backend-test`， it print below logs:

```
# gulp backend-test
[05:46:59] Requiring external module babel-register
[05:47:04] Using gulpfile /home/role/cameo/gulpfile.babel.js
[05:47:04] Starting 'clean-packaged-backend-source'...
[05:47:04] Finished 'clean-packaged-backend-source' after 35 ms
[05:47:04] Starting 'package-backend-source'...
[05:47:04] Finished 'package-backend-source' after 265 ms
[05:47:04] Starting 'link-vendor'...
[05:47:04] Finished 'link-vendor' after 413 μs
[05:47:04] Starting 'package-backend'...
[05:47:04] Finished 'package-backend' after 7.56 μs
[05:47:04] Starting 'backend-test'...
?       github.com/kubernetes/dashboard/src/app/backend [no test files]
ok      github.com/kubernetes/dashboard/src/app/backend/api     0.098s
ok      github.com/kubernetes/dashboard/src/app/backend/client  0.122s
ok      github.com/kubernetes/dashboard/src/app/backend/errors  0.120s
ok      github.com/kubernetes/dashboard/src/app/backend/handler 0.162s
2017/10/26 05:47:21 Using in-cluster config to connect to apiserver
2017/10/26 05:47:21 Could not init in cluster config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
2017/10/26 05:47:21 Using random key for csrf signing
2017/10/26 05:47:21 No request provided. Skipping authorization header
[restful] 2017/10/26 05:47:21 log.go:26: Could not create client config. Check logs for more information
2017/10/26 05:47:21 Skipping in-cluster config
2017/10/26 05:47:21 Using random key for csrf signing
2017/10/26 05:47:21 No request provided. Skipping authorization header
2017/10/26 05:47:21 Creating in-cluster Heapster client
an error on the server ("Error: 'dial tcp 172.17.0.9:8082: getsockopt: no route to host'\nTrying to reach: 'http://172.17.0.9:8082/healthz'") has prevented the request from succeeding (get services heapster)
2017/10/26 05:47:24 Skipping in-cluster config
2017/10/26 05:47:24 Using random key for csrf signing
2017/10/26 05:47:24 No request provided. Skipping authorization header
2017/10/26 05:47:24 Creating remote Heapster client for http://127.0.0.1:8081
--- FAIL: TestIntegrationManager_GetState (3.00s)
        manager_test.go:83: Test Case: Server provided and using in-cluster heapster. Expected state error to be: &{false 0001-01-01 00:00:00 +0000 UTC Get http://127.0.0.1:8080/api/v1/proxy/namespaces/kube-system/services/heapster/healthz: dial tcp 127.0.0.1:8080: getsockopt: connection refused}, but got &{false 2017-10-26 05:47:24.467433096 -0400 EDT an error on the server ("Error: 'dial tcp 172.17.0.9:8082: getsockopt: no route to host'\nTrying to reach: 'http://172.17.0.9:8082/healthz'") has prevented the request from succeeding (get services heapster)}.
FAIL
FAIL    github.com/kubernetes/dashboard/src/app/backend/integration     3.148s
?       github.com/kubernetes/dashboard/src/app/backend/integration/api [no test files]
ok      github.com/kubernetes/dashboard/src/app/backend/integration/metric      0.101s
?       github.com/kubernetes/dashboard/src/app/backend/integration/metric/api  [no test files]
ok      github.com/kubernetes/dashboard/src/app/backend/integration/metric/common       0.081s
ok      github.com/kubernetes/dashboard/src/app/backend/integration/metric/heapster     0.793s
?       github.com/kubernetes/dashboard/src/app/backend/resource/cluster        [no test files]
ok      github.com/kubernetes/dashboard/src/app/backend/resource/common 0.116s
?       github.com/kubernetes/dashboard/src/app/backend/resource/config [no test files]
ok      github.com/kubernetes/dashboard/src/app/backend/resource/configmap      0.152s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/container      0.123s
?       github.com/kubernetes/dashboard/src/app/backend/resource/controller     [no test files]
ok      github.com/kubernetes/dashboard/src/app/backend/resource/daemonset      0.178s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/dataselect     0.096s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/deployment     0.227s
?       github.com/kubernetes/dashboard/src/app/backend/resource/discovery      [no test files]
ok      github.com/kubernetes/dashboard/src/app/backend/resource/event  0.105s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/horizontalpodautoscaler        0.106s
?       github.com/kubernetes/dashboard/src/app/backend/resource/ingress        [no test files]
ok      github.com/kubernetes/dashboard/src/app/backend/resource/job    0.142s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/limitrange     0.080s
?       github.com/kubernetes/dashboard/src/app/backend/resource/logs   [no test files]
ok      github.com/kubernetes/dashboard/src/app/backend/resource/namespace      0.099s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/node   0.111s
?       github.com/kubernetes/dashboard/src/app/backend/resource/overview       [no test files]
ok      github.com/kubernetes/dashboard/src/app/backend/resource/persistentvolume       0.127s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/persistentvolumeclaim  0.103s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/pod    0.153s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/rbacrolebindings       0.139s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/rbacroles      0.155s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/replicaset     0.129s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/replicationcontroller  0.144s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/resourcequota  0.107s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/secret 0.105s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/service        0.137s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/statefulset    0.109s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/storageclass   0.166s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/thirdpartyresource     0.117s
ok      github.com/kubernetes/dashboard/src/app/backend/resource/workload       0.108s
?       github.com/kubernetes/dashboard/src/app/backend/scaling [no test files]
?       github.com/kubernetes/dashboard/src/app/backend/search  [no test files]
ok      github.com/kubernetes/dashboard/src/app/backend/validation      0.095s
[05:47:56] 'backend-test' errored after 52 s
[05:47:56] Error: Go command error, code: 1
    at Error (native)
    at ChildProcess.<anonymous> (/home/role/cameo/build/gocommand.js:199:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12) 
```

It seems that in-cluster heapster can't not be create 

##### Expected result

I expect `gulp backend-test` not throw error

##### Comments

 running `gulp serve` everything work fine and i can see the CPU Graph .

**Comment by maciaszczykm** [comment]
Backend tests pass on master:
https://travis-ci.org/kubernetes/dashboard/jobs/294841109

Dashboard 1.6.x may not be compatible with Kubernetes 1.5.x:
https://github.com/kubernetes/dashboard/wiki/Compatibility-matrix

We have not enough resources to support older Dashboard versions at the moment. There is a small possibility, that one of the versions may not pass backend tests, but it is very small since we are testing every build with CI before merging it.
