### ISSUE TITLE
SIGSEGV in dashboard 1.8.0 upon starting fresh

### ISSUE THREAD

**Issue by farcaller** [kubernetes/dashboard#2670]
##### Environment

```
Dashboard version: 1.8.0
Kubernetes version: 1.8.5
Operating system: Ubuntu 16.04
```

##### Steps to reproduce
Start the dashboard with a default deployment

##### Observed result
Dashboard crashes with:
```
2017/12/12 22:50:52 Starting overwatch
2017/12/12 22:50:52 Using in-cluster config to connect to apiserver
2017/12/12 22:50:52 Using service account token for csrf signing
2017/12/12 22:50:52 No request provided. Skipping authorization
2017/12/12 22:50:52 Successful initial request to the apiserver, version: v1.8.5
2017/12/12 22:50:52 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2017/12/12 22:50:52 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2017/12/12 22:50:52 Synchronized secret  has been deleted. Recreating.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x590c67]

goroutine 49 [running]:
crypto/rsa.(*PrivateKey).Precompute(0x0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/crypto/rsa/rsa.go:449 +0x37
crypto/x509.MarshalPKCS1PrivateKey(0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/crypto/x509/pkcs1.go:87 +0x43
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.ExportRSAKeyOrDie(0x0, 0x0, 0x32, 0x46, 0x80)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/util.go:28 +0x40
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).getEncryptionKeyHolder(0xc4204c5800, 0x34, 0xc420495ce8)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:137 +0x4e
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).recreate(0xc4204c5800, 0x1a63d60, 0xc42043d7c0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:110 +0xc8
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).(github.com/kubernetes/dashboard/src/app/backend/auth/jwe.recreate)-fm(0x1a63d60, 0xc42043d7c0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:116 +0x3e
github.com/kubernetes/dashboard/src/app/backend/sync.(*secretSynchronizer).handleEvent(0xc420052f00, 0x1279071, 0x7, 0x1a63d60, 0xc42043d7c0, 0xc420067f40, 0xc420495fa8)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/secret.go:189 +0xbd
github.com/kubernetes/dashboard/src/app/backend/sync.(*secretSynchronizer).Start.func1(0xc420052f00, 0x1a61960, 0xc42000a780)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/secret.go:78 +0x235
created by github.com/kubernetes/dashboard/src/app/backend/sync.(*secretSynchronizer).Start
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/secret.go:84 +0x11b
```

**Comment by floreks** [comment]
This was already fixed in #2639. We are starting release process for `v1.8.1` release today so it should be available in a couple of days.
