### ISSUE TITLE
dashboard development error

### ISSUE THREAD

**Issue by zhixingPan** [kubernetes/dashboard#2960]
##### Environment

```
Dashboard version:v1.8.3
Kubernetes version:17.09.0-ce
Operating system:ubuntu 16.04
Node.js version:v8.9.4
Go version: go1.10 
```

##### Steps to reproduce

1.I followed the document to build my dashboard  development environment.
2.I installed nodejs, npm and gulp ...
3.when I runed 'gulp serve' commom ,and visit 'localhost:9090', an error happend in the termial :
 '[HPM] Error occurred while trying to proxy request /api/appConfig.json from localhost:9090 to http://localhost:9091 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)'
 

##### Observed result

the result are below:
~/go/src/github.com/dashboard$ gulp serve
[16:39:16] Requiring external module babel-core/register
[16:39:18] Using gulpfile ~/go/src/github.com/dashboard/gulpfile.babel.js
[16:39:18] Starting 'clean-packaged-backend-source'...
[16:39:18] Starting 'kill-backend'...
[16:39:18] Finished 'kill-backend' after 168 μs
[16:39:18] Starting 'locales-for-backend:dev'...
[16:39:18] Starting 'scripts'...
[16:39:18] Starting 'styles'...
[16:39:18] Starting 'buildExistingI18nCache'...
[16:39:19] Finished 'buildExistingI18nCache' after 422 ms
[16:39:19] Starting 'angular-templates'...
[16:39:19] Finished 'locales-for-backend:dev' after 812 ms
[16:39:19] Finished 'clean-packaged-backend-source' after 863 ms
[16:39:19] Starting 'package-backend-source'...
[16:39:26] Finished 'scripts' after 7.82 s
[16:39:27] Finished 'styles' after 8.24 s
[16:39:27] Starting 'index'...
{ Error: easyfont-roboto-mono is not installed. Try running `bower install` or remove the component from your bower.json file.
    at /home/panzx/go/src/github.com/dashboard/node_modules/wiredep/lib/detect-dependencies.js:153:19
    at /home/panzx/go/src/github.com/dashboard/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/home/panzx/go/src/github.com/dashboard/node_modules/lodash/lodash.js:3001:24)
    at /home/panzx/go/src/github.com/dashboard/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/home/panzx/go/src/github.com/dashboard/node_modules/lodash/lodash.js:9359:14)
    at detectDependencies (/home/panzx/go/src/github.com/dashboard/node_modules/wiredep/lib/detect-dependencies.js:40:7)
    at wiredep (/home/panzx/go/src/github.com/dashboard/node_modules/wiredep/wiredep.js:71:39)
    at DestroyableTransform._transform (/home/panzx/go/src/github.com/dashboard/node_modules/wiredep/wiredep.js:137:34)
    at DestroyableTransform.Transform._read (/home/panzx/go/src/github.com/dashboard/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/home/panzx/go/src/github.com/dashboard/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/home/panzx/go/src/github.com/dashboard/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/panzx/go/src/github.com/dashboard/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/home/panzx/go/src/github.com/dashboard/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at DestroyableTransform.ondata (/home/panzx/go/src/github.com/dashboard/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:116:13)
    at DestroyableTransform.emit (events.js:211:7)
    at addChunk (/home/panzx/go/src/github.com/dashboard/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/home/panzx/go/src/github.com/dashboard/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at DestroyableTransform.Readable.push (/home/panzx/go/src/github.com/dashboard/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at DestroyableTransform.Transform.push (/home/panzx/go/src/github.com/dashboard/node_modules/readable-stream/lib/_stream_transform.js:146:32)
    at DestroyableTransform.<anonymous> (/home/panzx/go/src/github.com/dashboard/node_modules/gulp-inject/src/inject/index.js:88:12)
    at <anonymous>:null:null
    at process._tickCallback (internal/process/next_tick.js:188:7)
 code: 'PKG_NOT_INSTALLED' }
[16:39:27] Finished 'index' after 131 ms
[16:39:27] Finished 'angular-templates' after 8.06 s
[16:39:27] Starting 'watch'...
[16:39:27] Finished 'watch' after 523 ms
[16:39:27] Finished 'package-backend-source' after 8.36 s
[16:39:27] Starting 'link-vendor'...
[16:39:27] Finished 'link-vendor' after 629 μs
[16:39:27] Starting 'package-backend'...
[16:39:27] Finished 'package-backend' after 106 μs
[16:39:27] Starting 'backend'...
[16:39:28] Finished 'backend' after 557 ms
[16:39:28] Starting 'spawn-backend'...
[16:39:28] Finished 'spawn-backend' after 11 ms
[16:39:28] Starting 'serve'...
[HPM] Proxy created: /api  ->  http://localhost:9091
[16:39:28] Finished 'serve' after 27 ms
[BS] [BrowserSync SPA] Running...
[Browsersync] Access URLs:
 ---------------------------------------
       Local: http://localhost:9090/
    External: http://10.202.110.29:9090/
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://10.202.110.29:3001
 ---------------------------------------
2018/04/12 16:39:28 Starting overwatch
2018/04/12 16:39:28 Using apiserver-host location: https://10.202.70.69:6443
2018/04/12 16:39:28 Skipping in-cluster config
2018/04/12 16:39:28 Using random key for csrf signing
2018/04/12 16:39:28 No request provided. Skipping authorization
[Browsersync] Serving files from: /home/panzx/go/src/github.com/dashboard/.tmp/serve
[Browsersync] Serving files from: /home/panzx/go/src/github.com/dashboard/src/app
panic: host must be a URL or a host:port pair: "https://10.202.70.69:6443\n"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initInsecureClient(0xc420328360)
	/home/panzx/go/src/github.com/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/manager.go:335 +0x97
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc420328360)
	/home/panzx/go/src/github.com/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/manager.go:297 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(0x0, 0x0, 0x7ffdcc62ac3c, 0x1a, 0x1, 0x0)
	/home/panzx/go/src/github.com/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/manager.go:365 +0x84
main.main()
	/home/panzx/go/src/github.com/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:92 +0x131
[HPM] Error occurred while trying to proxy request /api/appConfig.json from localhost:9090 to http://localhost:9091 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by cheld** [comment]
Try to remove node_modules and bower and run npm install again. Restart computer to release all ports.

**Comment by floreks** [comment]
Closing as stale
