### ISSUE TITLE
Unable to use on the Mac

### ISSUE THREAD

**Issue by gopinatht** [kubernetes/dashboard#308]
1) git clone
2) npm install
3) gulp local-up-cluster

I get the following error on the third step:
`[17:34:10] Failed to load external module babel/register
/Users/Gopinath/Documents/Gopinath/dev/PrintStudioWrap/spark/dev/dashboard/gulpfile.babel.js:21
import './build/check';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)`

What am I doing wrong?

Thanks
Gopinath

**Comment by bryk** [comment]
What's your node version? 4+ is required.

**Comment by bryk** [comment]
The dev environment works on mac - I'm using mac.

**Comment by gopinatht** [comment]
@bryk I updated my node version to v5.4.1 and gulp is 3.9. NPM is 3.3.12. I deleted and cloned the repo again.

I am still getting this error:

`gulp local-up-cluster
[09:09:02] Failed to load external module babel/register
/Users/Gopinath/Documents/Gopinath/dev/PrintStudioWrap/spark/dev/dashboard/gulpfile.babel.js:21
import './build/check';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)`

Thanks for any help.

**Comment by gopinatht** [comment]
@bryk When I do npm install, I get these warnings:

`npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm`

**Comment by bryk** [comment]
With @luxas we've made it possible to have only docker to run this project. Basically we run our build system inside docker that has all dependencies. Try `./build/run-gulp-in-docker.sh serve`.

**Comment by bryk** [comment]
Do you start with npm install, btw?

**Comment by luxas** [comment]
I think this may be closed. @gopinatht use `./build/run-gulp-in-docker.sh serve` or just `kubectl create -f <manifest>` to spin up the `dashboard`

**Comment by gopinatht** [comment]
@luxas I have not tested it but I am ok to close it. I will test it this week and report back if I am not able to use the dashboard
