### ISSUE TITLE
Upgrade Request Required

### ISSUE THREAD

**Issue by kasunsjc** [kubernetes/dashboard#3083]
##### Environment

Dashboard version: v1.8.3
Kubernetes version:v.19.6
Operating system: ubuntu (Azure Kubunetes Service) 
Node.js version:
Go version:

##### Steps to reproduce

- Click the pod 
- in the pod click exec 

![image](https://user-images.githubusercontent.com/16514562/41154404-b0449002-6b37-11e8-8f35-7690d3695d03.png)

Above message prompt when the GUI command prompt comes

**Comment by siddharthlatest** [comment]
Seeing the same issue since some time now. This didn't use to always happen.

Dashboard Version:
v1.8.3
Git Commit:
ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c

Kubernetes Version: v1.9.6

**Comment by mrinalvirnave** [comment]
Its not limited to the dashboard. I am seeing other websocket connections fail in my AKS cluster in east-us. It seems to be working on west-us
```
Running shell script
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
    at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:219)
    at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:186)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by kasunsjc** [comment]
I updated my AKS cluster to newest version 1.10.3. Now issue is resolved
