### ISSUE TITLE
Unable to login using Azure AD 

### ISSUE THREAD

**Issue by sylr** [kubernetes/dashboard#3114]
```
Dashboard version: v1.8.3 
Kubernetes version: 1.10.2
Operating system: Ubuntu
Node.js version:
Go version:
```

I've a kubernetes cluster in Azure with authentication plugged into Azure AD. Everything works fine except the Dashboard login.

When I try to login by giving it my kube config file I get the following error `Not enough data to create auth info structure. ` and I see the following stack trace in the kube api server logs.

```
I0628 12:21:27.638196       1 wrap.go:42] GET /api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/api/v1/csrftoken/login: (10.055615ms) 200 [[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0] 217.109.68.123:28440]
I0628 12:21:27.702141       1 wrap.go:42] POST /api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/api/v1/login: (7.749211ms) 500
goroutine 55043527 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc423eec9a0, 0x1f4)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc423eec9a0, 0x1f4)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.(*auditResponseWriter).WriteHeader(0xc43b5785f0, 0x1f4)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:220 +0x63
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc4350079b0, 0x1f4)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:281 +0x45
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc431cc5c80, 0xb1e1a20, 0xc42f8c0e68, 0xc433e2f600)
        /usr/local/go/src/net/http/httputil/reverseproxy.go:243 +0x691
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy.(*UpgradeAwareHandler).ServeHTTP(0xc43770cc00, 0xb1e1a20, 0xc42f8c0e68, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go:231 +0x809
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ConnectResource.func1.1()
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:143 +0x263
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.RecordLongRunning(0xc42e980c00, 0xc42a6e2e70, 0xc432d94210)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:155 +0x1c8
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ConnectResource.func1(0xb1e1a20, 0xc42f8c0e68, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:137 +0x387
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulConnectResource.func1(0xc435007920, 0xc43092baa0)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1069 +0xe0
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc435007920, 0xc43092baa0)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:199 +0x208
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc42085e360, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0xb18
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc42085e360, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4cad99a, 0xe, 0xc42085e360, 0xc4214b8930, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:152 +0x4e0
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc42149b220, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        <autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc42dad9980, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:93 +0x18a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc426a83940, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x26d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc421a77c00, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4cb1619, 0xf, 0xc42aa38750, 0xc421a77c00, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:160 +0x6ad
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc42aa483a0, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        <autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:52 +0x37d
net/http.HandlerFunc.ServeHTTP(0xc422546aa0, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:131 +0x515
net/http.HandlerFunc.ServeHTTP(0xc42aa23000, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x203a
net/http.HandlerFunc.ServeHTTP(0xc422546b90, 0xb1e1920, 0xc42f8c0e50, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAudit.func1(0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:105 +0x501
net/http.HandlerFunc.ServeHTTP(0xc422546c80, 0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:78 +0x2b1
net/http.HandlerFunc.ServeHTTP(0xc422546dc0, 0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc42aa483c0, 0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc42aa48440, 0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:86 +0x422
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:51 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc42aa23040, 0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x20f
net/http.HandlerFunc.ServeHTTP(0xc42aa23080, 0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc42aa48460, 0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0xb1e1aa0, 0xc423eec9a0, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x108
net/http.HandlerFunc.ServeHTTP(0xc42aa48480, 0xb1e3420, 0xc42f8c0e48, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc42aa3bc50, 0xb1e3420, 0xc42f8c0e48, 0xc42e980c00)
        /workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:197 +0x51
net/http.serverHandler.ServeHTTP(0xc428d3e000, 0xb1e3420, 0xc42f8c0e48, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.initNPNRequest.ServeHTTP(0xc435a14000, 0xc428d3e000, 0xb1e3420, 0xc42f8c0e48, 0xc42e980c00)
        /usr/local/go/src/net/http/server.go:3164 +0x9a
net/http.(*initNPNRequest).ServeHTTP(0xc42511c9e0, 0xb1e3420, 0xc42f8c0e48, 0xc42e980c00)
        <autogenerated>:1 +0x63
net/http.(Handler).ServeHTTP-fm(0xb1e3420, 0xc42f8c0e48, 0xc42e980c00)
        /usr/local/go/src/net/http/h2_bundle.go:5462 +0x4d
net/http.(*http2serverConn).runHandler(0xc426123500, 0xc42f8c0e48, 0xc42e980c00, 0xc42920d620)
        /usr/local/go/src/net/http/h2_bundle.go:5747 +0x89
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5481 +0x495

logging error output: "\x1f\x8b\b\x00\x00\x00\x00\x00\x04\xff\x00)\x00\xd6\xffNot enough data to create authenticator.\n\x01\x00\x00\xff\xffMJ:/)\x00\x00\x00"
```

**Comment by floreks** [comment]
As per [documentation](https://github.com/kubernetes/dashboard/wiki/Access-control#kubeconfig):
```
Kubeconfig

This method of logging in is provided for convenience. Only authentication options specified by --authentication-mode flag are supported in kubeconfig file. In case it is configured to use any other way, error will be shown in Dashboard. External identity providers or certificate-based authentication are not supported at this time.
```

This means that only token and basic auth can be used inside the kubeconfig file to log in at the moment.

**Comment by joberget** [comment]
@floreks  Is it on the roadmap to support Active Directory?

**Comment by floreks** [comment]
At first, we want to add support for OAuth 2.0 standard, so any application that supports it will be able to work with Dashboard. There is no ETA though.

**Comment by imranrazakhan** [comment]
@sylr  Following guide works well for Azure AD
[](https://github.com/weinong/k8s-dashboard-with-aks-aad )
