### ISSUE TITLE
dashboard can't build on debian jessie

### ISSUE THREAD

**Issue by zhangwen-qq** [kubernetes/dashboard#315]
I have all versions of requirements already, but still can't build dashboard. Maybe I missed something else?

```
root@docker-django:~# docker --version
Docker version 1.9.0, build 76d6bc9
root@docker-django:~# go version
go version go1.5.3 linux/amd64
root@docker-django:~# nodejs --version
v5.5.0
root@docker-django:~# npm --version
3.3.12
root@docker-django:~# javac -version
javac 1.7.0_91
root@docker-django:~# gulp --version
[10:54:03] CLI version 3.9.0
[10:54:03] Local version 3.9.0
```

and the output is like this:
```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: Command failed: java -jar -XX:+TieredCompilation /data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/compiler.jar --flagfile="/tmp/f9b67634-af70-41bc-8938-9b05f12836f9" --angular_pass --closure_entry_p
oint=module$index_module --compilation_level=ADVANCED_OPTIMIZATIONS --export_local_property_definitions --externs=/data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-1.4.js --externs=/
data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-1.4-http-promise_templated.js --externs=/data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/exte
rns/angular-1.4-q_templated.js --externs=/data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-material.js --externs=/data/tools/github.com/kubernetes/dashboard/node_modules/google-closu
re-compiler/contrib/externs/angular_ui_router.js --externs=/data/tools/github.com/kubernetes/dashboard/node_modules/google-closure-compiler/contrib/externs/angular-1.4-resource.js --externs=/data/tools/github.com/kubernetes/dashboard/src
/app/externs/backendapi.js --generate_exports --js_module_root=src/app/frontend --jscomp_error=* --jscomp_off=inferredConstCheck --jscomp_off=lintChecks --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT3 --manage_closure_depende
ncies=true --use_types_for_optimization --js_output_file="app.js"
src/app/frontend/logs/logstoolbar/logstoolbar_controller.js:80: ERROR - variable goog is undeclared
  isTextColorInverted() { return this.logsColorInversionService_.getInverted(); }
  ^

1 error(s), 0 warning(s), 96.0% typed
java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

Unexpected variable goog
  Node(NAME goog): src/app/frontend/logs/logstoolbar/logstoolbar_controller.js:80:2
  isTextColorInverted() { return this.logsColorInversionService_.getInverted(); }
  Parent(GETPROP): src/app/frontend/logs/logstoolbar/logstoolbar_controller.js:80:2
  isTextColorInverted() { return this.logsColorInversionService_.getInverted(); }

        at com.google.javascript.jscomp.VarCheck.visit(VarCheck.java:202)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:621)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:615)
        at com.google.javascript.jscomp.NodeTraversal.traverseRoots(NodeTraversal.java:316)
        at com.google.javascript.jscomp.VarCheck.process(VarCheck.java:142)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
        at com.google.javascript.jscomp.Compiler.optimize(Compiler.java:1943)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:700)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:651)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:648)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unexpected variable goog
        ... 21 more

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by bryk** [comment]
@cheld @floreks @maciaszczykm Can you guys help here?

**Comment by maciaszczykm** [comment]
@zhangwen-qq Software versions, that you have listed seem to be alright. Mine are almost the same:

```
maciaszczykm:~/workspace$ docker --version
Docker version 1.9.1, build a34a1d5
maciaszczykm:~/workspace$ go version
go version go1.5.1 linux/amd64
maciaszczykm:~/workspace$ nvm version
v5.5.0
maciaszczykm:~/workspace$ node --version
v5.5.0
maciaszczykm:~/workspace$ npm --version
3.3.12
maciaszczykm:~/workspace$ javac -version
javac 1.7.0_91
maciaszczykm:~/workspace$ gulp --version
[12:58:03] Requiring external module babel-core/register
[12:58:03] CLI version 3.9.0
[12:58:03] Local version 3.9.0
```

Which exact command fails? Have you tried using [creationix/nvm](https://github.com/creationix/nvm) to get proper node.js version? What system are you using? Have you tried executing commands as reqular user, not as a root? Perhaps there is sommething missing in root enviroment.

**Comment by luxas** [comment]
I've encountered this. You have to run `bower install`
`sudo npm install ` doesn't run `bower install` if it's root (don't ask me why)

**Comment by zhangwen-qq** [comment]
@bryk @maciaszczykm @luxas
Tried bower install and it works. 
Really appreciate all your help! This saved me tones of time.
It's comfortable to use dashboard, Good Job

**Comment by zhangwen-qq** [comment]
@bryk @maciaszczykm @luxas
Tried bower install and it works. 
Really appreciate all your help! This saved me tones of time.
It's comfortable to use dashboard, Good Job
