### ISSUE TITLE
Getting error building dashboard (Unhandled 'error' event)

### ISSUE THREAD

**Issue by tathagatkhanorkar** [kubernetes/dashboard#3467]
##### Environment

```
Installation method: 

Step 1:- git clone https://github.com/kubernetes/dashboard
Step 2:- npm install
Step 3:- npm start

Dashboard version:
Using master branch of https://github.com/kubernetes/dashboard

Operating system:
Windows 10 64-bit
Node.js version ('node --version' output):
node --version
v9.10.1

npm -v
6.6.0-next.0

gulp -v
[18:55:27] Failed to load external module @babel/register
[18:55:27] Requiring external module babel-register
[18:55:27] CLI version 3.9.1
[18:55:27] Local version 3.9.1

Go version ('go version' output):

go version
go version go1.11 windows/amd64

```

##### Steps to reproduce

```
npm install


> kubernetes-dashboard@2.0.0-alpha0 postinstall C:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard
> node aio/scripts/version.js && webdriver-manager update && go get golang.org/x/tools/cmd/goimports

Version v1.10.1-107-gb92f25a-dirty saved to ..\src\app\frontend\environments\version.ts
webdriver-manager: using local installed version 12.1.1
[18:59:30] I/config_source - curl -oC:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard\node_modules\webdriver-manager\selenium\standalone-response.xml https://sel
enium-release.storage.googleapis.com/
[18:59:31] I/config_source - curl -oC:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromed
river.storage.googleapis.com/
[18:59:31] I/config_source - curl -oC:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard\node_modules\webdriver-manager\selenium\gecko-response.json https://api.git
hub.com/repos/mozilla/geckodriver/releases
[18:59:34] I/update - chromedriver: file exists C:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard\node_modules\webdriver-manager\selenium\chromedriver_2.45.zip
[18:59:34] I/update - chromedriver: unzipping chromedriver_2.45.zip
[18:59:34] I/update - chromedriver: chromedriver_2.45.exe up to date
[18:59:34] I/update - selenium standalone: file exists C:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard\node_modules\webdriver-manager\selenium\selenium-server-
standalone-3.141.59.jar
[18:59:34] I/update - selenium standalone: selenium-server-standalone-3.141.59.jar up to date
[18:59:42] I/update - geckodriver: file exists C:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard\node_modules\webdriver-manager\selenium\geckodriver-v0.23.0.zip
[18:59:42] I/update - geckodriver: unzipping geckodriver-v0.23.0.zip
[18:59:42] I/update - geckodriver: geckodriver-v0.23.0.exe up to date
npm WARN @babel/register@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@6.0.8 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uirouter/angular@2.0.2 requires a peer of @angular/common@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uirouter/angular@2.0.2 requires a peer of @angular/core@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @uirouter/angular@2.0.2 requires a peer of @angular/router@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ace-editor@0.3.8 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-linux@20181210.0.0 (node_modules\google-closure-compiler-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-linux@20181210.0.0: wanted {"os":"linux","arch":"x64,x86"} (current: {"os":"win32","arch":"
x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-osx@20181210.0.0 (node_modules\google-closure-compiler-osx):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-osx@20181210.0.0: wanted {"os":"darwin","arch":"x64,x86"} (current: {"os":"win32","arch":"x
64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 45430 packages in 88.436s
found 6 vulnerabilities (1 low, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

```

npm start

> kubernetes-dashboard@2.0.0-alpha0 start C:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard
> concurrently "npm run start:backend" "npm run start:frontend"

[0]
[0] > kubernetes-dashboard@2.0.0-alpha0 start:backend C:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard
[0] > gulp serve --kubeconfig $npm_package_config_kubeconfig
[0]
[1]
[1] > kubernetes-dashboard@2.0.0-alpha0 start:frontend C:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard
[1] > npm run postversion && ng serve --aot --progress=false --proxy-config aio/proxy.conf.json --host=0.0.0.0
[1]
[1]
[1] > kubernetes-dashboard@2.0.0-alpha0 postversion C:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard
[1] > node aio/scripts/version.js
[1]
[1] Version v1.10.1-107-gb92f25a-dirty saved to ..\src\app\frontend\environments\version.ts
[0] [19:03:20] Failed to load external module @babel/register
[0] [19:03:20] Requiring external module babel-register
[0] [19:03:24] Using gulpfile ~\go\src\github.com\kubernetes\dashboard\gulpfile.babel.js
[0] [19:03:24] Starting 'clean-packaged-backend-source'...
[0] [19:03:24] Starting 'kill-backend'...
[0] [19:03:24] Finished 'kill-backend' after 359 μs
[0] [19:03:24] Starting 'locales-for-backend:dev'...
[0] [19:03:24] Starting 'watch'...
[0] [19:03:31] Finished 'watch' after 6.71 s
[0] [19:03:31] Finished 'locales-for-backend:dev' after 7.12 s
[0] [19:03:31] Finished 'clean-packaged-backend-source' after 7.18 s
[0] [19:03:31] Starting 'package-backend-source'...
[0] [19:03:32] Finished 'package-backend-source' after 1.25 s
[0] [19:03:32] Starting 'link-vendor'...
[0] [19:03:32] Finished 'link-vendor' after 823 μs
[0] [19:03:32] Starting 'package-backend'...
[0] [19:03:32] Finished 'package-backend' after 28 μs
[0] [19:03:32] Starting 'backend'...
[1] ** Angular Live Development Server is listening on 0.0.0.0:8080, open your browser on http://localhost:8080/ **
[0] [19:04:37] Finished 'backend' after 1.07 min
[0] [19:04:37] Starting 'spawn-backend'...
[0] [19:04:37] Finished 'spawn-backend' after 11 ms
[0] [19:04:37] Starting 'serve'...
[0] [19:04:37] Finished 'serve' after 2.6 μs

*************************************************************
[0] events.js:165
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: spawn C:\Users\tathagat.khanorkar\go\src\github.com\kubernetes\dashboard\.tmp\serve\dashboard ENOENT
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
[0]     at onErrorNT (internal/child_process.js:379:16)
[0]     at process._tickCallback (internal/process/next_tick.js:114:19)
[0] Emitted 'error' event at:
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
[0]     at onErrorNT (internal/child_process.js:379:16)
[0]     at process._tickCallback (internal/process/next_tick.js:114:19)
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! kubernetes-dashboard@2.0.0-alpha0 start:backend: `gulp serve --kubeconfig $npm_package_config_kubeconfig`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the kubernetes-dashboard@2.0.0-alpha0 start:backend script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     C:\Users\tathagat.khanorkar\AppData\Roaming\npm-cache\_logs\2018-12-26T13_34_37_904Z-debug.log
[0] npm run start:backend exited with code 1 
*************************************************************
```
```
[1] Date: 2018-12-26T13:36:59.902Z
[1] Hash: 0e46d2617ac657724346
[1] Time: 166194ms
...
...
...
...
[1] chunk {styles} styles.js, styles.js.map (styles) 247 kB [initial] [rendered]
[1] chunk {vendor} vendor.js, vendor.js.map (vendor) 8.61 MB [initial] [rendered]
[1] i ｢wdm｣: Compiled successfully.
[1] [HPM] Error occurred while trying to proxy request /config from localhost:8080 to http://localhost:9090 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors
)
[1] [HPM] Error occurred while trying to proxy request /api/v1/settings/global/cani from localhost:8080 to http://localhost:9090 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors
_common_system_errors)
[1] [HPM] Error occurred while trying to proxy request /api/v1/systembanner from localhost:8080 to http://localhost:9090 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_
system_errors)
[1] [HPM] Error occurred while trying to proxy request /api/v1/login/status from localhost:8080 to http://localhost:9090 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_
system_errors)
[1] [HPM] Error occurred while trying to proxy request /api/v1/namespace from localhost:8080 to http://localhost:9090 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_sys
tem_errors)
[1] [HPM] Error occurred while trying to proxy request /api/v1/settings/global/cani from localhost:8080 to http://localhost:9090 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors
_common_system_errors)
[1] [HPM] Error occurred while trying to proxy request /api/v1/login/status from localhost:8080 to http://localhost:9090 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_
system_errors)
[1] [HPM] Error occurred while trying to proxy request /api/v1/settings/global/cani from localhost:8080 to http://localhost:9090 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors
_common_system_errors)



```

##### Expected result

```

[0] [19:08:24] Failed to load external module @babel/register
[0] [19:08:24] Requiring external module babel-register
[0] [19:08:26] Using gulpfile ~/go/src/github.com/kubernetes/dashboard/gulpfile.babel.js
[0] [19:08:27] Starting 'clean-packaged-backend-source'...
[0] [19:08:27] Starting 'kill-backend'...
[0] [19:08:27] Finished 'kill-backend' after 877 μs
[0] [19:08:27] Starting 'locales-for-backend:dev'...
[0] [19:08:27] Starting 'watch'...
[0] [19:08:28] Finished 'watch' after 1.25 s
[0] [19:08:28] Finished 'clean-packaged-backend-source' after 1.41 s
[0] [19:08:28] Starting 'package-backend-source'...
[0] [19:08:28] Finished 'locales-for-backend:dev' after 1.7 s
[0] [19:08:30] Finished 'package-backend-source' after 1.48 s
[0] [19:08:30] Starting 'link-vendor'...
[0] [19:08:30] Finished 'link-vendor' after 1.27 ms
[0] [19:08:30] Starting 'package-backend'...
[0] [19:08:30] Finished 'package-backend' after 32 μs
[0] [19:08:30] Starting 'backend'...
[1] ** Angular Live Development Server is listening on 0.0.0.0:8080, open your browser on http://localhost:8080/ **
[0] [19:08:52] Finished 'backend' after 23 s
[0] [19:08:52] Starting 'spawn-backend'...
[0] [19:08:52] Finished 'spawn-backend' after 41 ms
[0] [19:08:52] Starting 'serve'...
[0] [19:08:52] Finished 'serve' after 10 μs
[0] 2018/12/26 19:08:52 Starting overwatch
[0] 2018/12/26 19:08:52 Using kubeconfig file: /root/.kube/config
[0] 2018/12/26 19:08:52 Skipping in-cluster config
[0] 2018/12/26 19:08:52 Using random key for csrf signing
[0] 2018/12/26 19:08:52 Successful initial request to the apiserver, version: v1.13.1
[0] 2018/12/26 19:08:52 Generating JWE encryption key
[0] 2018/12/26 19:08:52 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
[0] 2018/12/26 19:08:52 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
[0] 2018/12/26 19:08:56 Initializing JWE encryption key from synchronized object
[0] 2018/12/26 19:08:56 Creating in-cluster Heapster client
[0] 2018/12/26 19:08:56 Serving insecurely on HTTP port: 9090

```

##### Comments

I don't know how to produce expected results.
Following is the image of the error I am getting
```
Error undefined (undefined)
```
Here I am going to link [http://localhost:8080](url) and it is redirecting me to [http://localhost:8080/#/error?namespace=default](url).

Can anyone help me how to solve it?????
PS- Error part is between asterisks sign (*).
![issue dashboard](https://user-images.githubusercontent.com/45235109/50447757-5a107e80-0943-11e9-87bd-50379c68f6a2.jpg)

**Comment by maciaszczykm** [comment]
We do not support dev on Windows.
