### ISSUE TITLE
kube-dashboard build error

### ISSUE THREAD

**Issue by qiyongxiao** [kubernetes/dashboard#4073]
I execute ```npm ci``` return success. and I run ```npm run build```get some errors like this:
```
Building backend
[05:25:22] Requiring external module babel-register
[05:25:23] Using gulpfile ~/GolandProjects/dashboard/gulpfile.babel.js
[05:25:23] Starting 'backend:prod'...
[05:25:23] Starting '<anonymous>'...
# github.com/kubernetes/dashboard/src/app/backend
src/app/backend/dashboard.go:175:26: undefined: prometheus.Handler
[05:25:53] '<anonymous>' errored after 30 s
[05:25:53] Error: Go command error, code: 2
    at ChildProcess.<anonymous> (/Users/miyamoto/GolandProjects/dashboard/aio/gulp/gocommand.js:148:23)
    at ChildProcess.emit (events.js:203:13)
    at ChildProcess.EventEmitter.emit (domain.js:494:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[05:25:53] 'backend:prod' errored after 30 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-dashboard@2.0.0-beta1 build: `./aio/scripts/build.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kubernetes-dashboard@2.0.0-beta1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miyamoto/.npm/_logs/2019-07-17T21_25_53_392Z-debug.log
```

**Comment by floreks** [comment]
Dashboard requires Go 1.12+ with go modules feature enabled.

**Comment by qiyongxiao** [comment]
> Dashboard requires Go 1.12+ with go modules feature enabled.

my go language version is
```
miyamoto@macbookpro ~ % go version
go version go1.12.6 darwin/amd64

```

**Comment by floreks** [comment]
> my go language version is
>
> ```
> miyamoto@macbookpro ~ % go version
> go version go1.12.6 darwin/amd64
> ```

Try `export GO111MODULE=on` before running build.

**Comment by smartkuk** [comment]
> @qiyongxiao
> 
> Try `export GO111MODULE=on` before running build.

I had same issues, but Your solution save my day
[I wrote same issue but close](https://github.com/kubernetes/dashboard/issues/4102#issue-470955267)

**Comment by smartkuk** [comment]
I had same issues, but @floreks 's solution save my day
[I wrote same issue but close](https://github.com/kubernetes/dashboard/issues/4102#issue-470955267)

**Comment by qiyongxiao** [comment]
> /close

I meet these error like this:
```
 37% building 233/234 modules 1 active ...ashboard/src/app/frontend/index.scss
<--- Last few GCs --->

[44206:0x3e3e100]   107527 ms: Mark-sweep 886.7 (940.9) -> 877.1 (944.1) MB, 904.3 / 0.0 ms  (average mu = 0.259, current mu = 0.243) allocation failure scavenge might not succeed
[44206:0x3e3e100]   108762 ms: Mark-sweep 889.8 (944.1) -> 881.1 (944.9) MB, 1177.7 / 0.0 ms  (average mu = 0.151, current mu = 0.046) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13162b9]
    1: StubFrame [pc: 0x136e87e]
Security context: 0x0190cde00911 <JSObject>
    2: /* anonymous */(aka /* anonymous */) [0x22fb75b9f501] [/root/go/src/github.com/kubernetes/dashboard/node_modules/@angular/compiler/bundles/compiler.umd.js:23167] [bytecode=0x1cc744cf9661 offset=225](this=0x2e174eac04d1 <undefined>,0x3c2cfc99cd81 <JSFunction nodes.<computed> (sfi = 0x1cc744cf16e9)>,20)
    3: map [0x190cde09...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20190728.210740.44206.0.001.json
Node.js report completed
 1: 0x9aedf0 node::Abort() [ng build --aot --prod --outputPath=/root/go/src/github.com/kubernetes/dashboard/.tmp/frontend/en]
 2: 0x9aff86 node::OnFatalError(char const*, char const*) [ng build --aot --prod --outputPath=/root/go/src/github.com/kubernetes/dashboard/.tmp/frontend/en]
 3: 0xb078ce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [ng build --aot --prod --outputPath=/root/go/src/github.com/kubernetes/dashboard/.tmp/frontend/en]
 4: 0xb07c49 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [ng build --aot --prod --outputPath=/root/go/src/github.com/kubernetes/dashboard/.tmp/frontend/en]
 5: 0xce4ae5  [ng build --aot --prod --outputPath=/root/go/src/github.com/kubernetes/dashboard/.tmp/frontend/en]
 6: 0xcf032b v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [ng build --aot --prod --outputPath=/root/go/src/github.com/kubernetes/dashboard/.tmp/frontend/en]
 7: 0xcf1047 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [ng build --aot --prod --outputPath=/root/go/src/github.com/kubernetes/dashboard/.tmp/frontend/en]
 8: 0xcf3b78 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [ng build --aot --prod --outputPath=/root/go/src/github.com/kubernetes/dashboard/.tmp/frontend/en]
 9: 0xcbd487 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType) [ng build --aot --prod --outputPath=/root/go/src/github.com/kubernetes/dashboard/.tmp/frontend/en]
10: 0xf94048 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [ng build --aot --prod --outputPath=/root/go/src/github.com/kubernetes/dashboard/.tmp/frontend/en]
11: 0x13162b9  [ng build --aot --prod --outputPath=/root/go/src/github.com/kubernetes/dashboard/.tmp/frontend/en]
./aio/scripts/build.sh: 行 31: 44206 已放弃               (吐核)${NG_BIN} build --aot --prod --outputPath=${TMP_DIR}/frontend/en
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! kubernetes-dashboard@2.0.0-beta2 build: `./aio/scripts/build.sh`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the kubernetes-dashboard@2.0.0-beta2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-28T13_07_47_324Z-debug.log
```
How to solve it?

**Comment by jeefy** [comment]
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Looks like the process is running out of memory during the build. This sounds like an issue with your environment and not the Dashboard itself.

**Comment by qiyongxiao** [comment]
> > FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
> 
> Looks like the process is running out of memory during the build. This sounds like an issue with your environment and not the Dashboard itself.

##After I add memory, I run again for some error
```
miyamoto@macbookpro dashboard % npm run build

> kubernetes-dashboard@2.0.0-beta1 build /Users/miyamoto/GolandProjects/dashboard
> ./aio/scripts/build.sh


> kubernetes-dashboard@2.0.0-beta1 postversion /Users/miyamoto/GolandProjects/dashboard
> node aio/scripts/version.js

Version v2.0.0-beta1-21-gfcf712d21-dirty saved to ../src/app/frontend/environments/version.ts

Building backend
[06:16:44] Requiring external module babel-register
[06:16:45] Using gulpfile ~/GolandProjects/dashboard/gulpfile.babel.js
[06:16:45] Starting 'backend:prod'...
[06:16:45] Starting '<anonymous>'...
# github.com/kubernetes/dashboard/src/app/backend
src/app/backend/dashboard.go:175:26: undefined: prometheus.Handler
[06:17:19] '<anonymous>' errored after 34 s
[06:17:19] Error: Go command error, code: 2
    at ChildProcess.<anonymous> (/Users/miyamoto/GolandProjects/dashboard/aio/gulp/gocommand.js:148:23)
    at ChildProcess.emit (events.js:203:13)
    at ChildProcess.EventEmitter.emit (domain.js:494:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[06:17:19] 'backend:prod' errored after 34 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-dashboard@2.0.0-beta1 build: `./aio/scripts/build.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kubernetes-dashboard@2.0.0-beta1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miyamoto/.npm/_logs/2019-07-28T22_17_19_757Z-debug.log
```

**Comment by Frodez** [comment]
> > > FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
> > 
> > 
> > Looks like the process is running out of memory during the build. This sounds like an issue with your environment and not the Dashboard itself.
> 
> ##After I add memory, I run again for some error
> 
> ```
> miyamoto@macbookpro dashboard % npm run build
> 
> > kubernetes-dashboard@2.0.0-beta1 build /Users/miyamoto/GolandProjects/dashboard
> > ./aio/scripts/build.sh
> 
> 
> > kubernetes-dashboard@2.0.0-beta1 postversion /Users/miyamoto/GolandProjects/dashboard
> > node aio/scripts/version.js
> 
> Version v2.0.0-beta1-21-gfcf712d21-dirty saved to ../src/app/frontend/environments/version.ts
> 
> Building backend
> [06:16:44] Requiring external module babel-register
> [06:16:45] Using gulpfile ~/GolandProjects/dashboard/gulpfile.babel.js
> [06:16:45] Starting 'backend:prod'...
> [06:16:45] Starting '<anonymous>'...
> # github.com/kubernetes/dashboard/src/app/backend
> src/app/backend/dashboard.go:175:26: undefined: prometheus.Handler
> [06:17:19] '<anonymous>' errored after 34 s
> [06:17:19] Error: Go command error, code: 2
>     at ChildProcess.<anonymous> (/Users/miyamoto/GolandProjects/dashboard/aio/gulp/gocommand.js:148:23)
>     at ChildProcess.emit (events.js:203:13)
>     at ChildProcess.EventEmitter.emit (domain.js:494:23)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
> [06:17:19] 'backend:prod' errored after 34 s
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! kubernetes-dashboard@2.0.0-beta1 build: `./aio/scripts/build.sh`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the kubernetes-dashboard@2.0.0-beta1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/miyamoto/.npm/_logs/2019-07-28T22_17_19_757Z-debug.log
> ```

You should run npm build like this: sudo "PATH=$PATH" npm run build. Because golang is not be found before you add the PATH.
