### ISSUE TITLE
error   "postinstall": "node aio/scripts/version.js && ./node_modules/protractor/bin/webdriver-manager update --gecko=false --versions.standalone=3.141.59 && curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1"   

### ISSUE THREAD

**Issue by lubing2019** [kubernetes/dashboard#4093]
npm install  "postinstall": "node aio/scripts/version.js && ./node_modules/protractor/bin/webdriver-manager update --gecko=false --versions.standalone=3.141.59 && curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1"
  
error:

[2/6] scripts.postinstall babel-register@6.26.0 › core-js@^2.5.0 finished in 79ms
[3/6] scripts.install husky@3.0.0 run "node husky install", root: "/opt/dashboard-master/node_modules/_husky@3.0.0@husky"
husky > Setting up git hooks
fatal: Not a git repository (or any of the parent directories): .git
husky > Failed to install
[3/6] scripts.install husky@3.0.0 finished in 166ms
[3/6] scripts.postinstall husky@3.0.0 run "opencollective-postinstall || true", root: "/opt/dashboard-master/node_modules/_husky@3.0.0@husky"
Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

[3/6] scripts.postinstall husky@3.0.0 finished in 92ms
[4/6] scripts.postinstall @angular/cli@8.1.2 run "node ./bin/postinstall/script.js", root: "/opt/dashboard-master/node_modules/_@angular_cli@8.1.2@@angular/cli"
[4/6] scripts.postinstall @angular/cli@8.1.2 finished in 614ms
[5/6] scripts.install node-sass@4.12.0 run "node scripts/install.js", root: "/opt/dashboard-master/node_modules/_node-sass@4.12.0@node-sass"
Cached binary found at /root/.npminstall_tarball/node-sass/4.12.0/linux-x64-67_binding.node
[5/6] scripts.install node-sass@4.12.0 finished in 378ms
[5/6] scripts.postinstall node-sass@4.12.0 run "node scripts/build.js", root: "/opt/dashboard-master/node_modules/_node-sass@4.12.0@node-sass"
Binary found at /opt/dashboard-master/node_modules/_node-sass@4.12.0@node-sass/vendor/linux-x64-67/binding.node
Testing binary
Binary is fine
[5/6] scripts.postinstall node-sass@4.12.0 finished in 284ms
[6/6] scripts.postinstall kubernetes-dashboard@2.0.0-beta2 run "node aio/scripts/version.js && curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1", root: "/opt/dashboard-master"
/opt/dashboard-master/node_modules/_git-describe@4.0.4@git-describe/lib/git-describe.js:81
        throw err;
        ^

Error: Git returned with status 128: fatal: Not a git repository (or any of the parent directories): .git
    at handleProcessResult (/opt/dashboard-master/node_modules/_git-describe@4.0.4@git-describe/lib/git-describe.js:76:19)
    at wrapper (/opt/dashboard-master/node_modules/_lodash@4.17.15@lodash/lodash.js:5193:19)
    at gitDescribe (/opt/dashboard-master/node_modules/_git-describe@4.0.4@git-describe/lib/git-describe.js:46:16)
    at wrapper (/opt/dashboard-master/node_modules/_lodash@4.17.15@lodash/lodash.js:5193:19)
    at Object.<anonymous> (/opt/dashboard-master/aio/scripts/version.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)

**Comment by floreks** [comment]
No steps to reproduce. No actual description of the error and how it was encountered. Issue form not filled.

/close
