### ISSUE TITLE
Segmentation fault when running on some nodes

### ISSUE THREAD

**Issue by carsonoid** [kubernetes/dashboard#4476]
### Environment

I'm running an EKS cluster with a ~5 nodes.  I have been using the dashboard without issue for a few weeks now. However the dashboard suddenly started crashing while trying to load the login page. The strange thing is, it only crashes when running one one specific node. If I delete the pod and and let a new one get scheduled on a different node, then the dashboard works just fine.

```
Installation method: EKS
Kubernetes version: v1.13.10-eks-5ac0f1
Dashboard version: v1.10.1
Operating system: Linux
```

##### Steps to reproduce

I am unable to reproduce this anywhere except for a single node in my cluster. I am going to replace the node to fix it going forward. But it would be nice to know why this is happening in the first place. 

##### Verbose crash log
```
2019/10/29 15:30:11 Starting overwatch
2019/10/29 15:30:11 Using in-cluster config to connect to apiserver
2019/10/29 15:30:11 Using service account token for csrf signing
2019/10/29 15:30:11 Successful initial request to the apiserver, version: v1.13.10-eks-5ac0f1
2019/10/29 15:30:11 Generating JWE encryption key
2019/10/29 15:30:11 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2019/10/29 15:30:11 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2019/10/29 15:30:12 Initializing JWE encryption key from synchronized object
2019/10/29 15:30:12 Creating in-cluster Heapster client
2019/10/29 15:30:12 Serving securely on HTTPS port: 8443
2019/10/29 15:30:12 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
2019/10/29 15:30:34 Getting application global configuration
2019/10/29 15:30:34 Application configuration {"serverTime":1572363034446}
unexpected fault address 0x2f736a73
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2f736a73 pc=0x783079]

goroutine 15 [running]:
runtime.throw(0x121336e, 0x5)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/panic.go:616 +0x81 fp=0xc4204faf70 sp=0xc4204faf50 pc=0x429b81
runtime.sigpanic()
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/signal_unix.go:395 +0x211 fp=0xc4204fafc0 sp=0xc4204faf70 pc=0x43e6c1
github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful.Route.matchesAccept(0x12126a2, 0x3, 0xc420272400, 0x1, 0x1, 0xc4202723f0, 0x1, 0x1, 0xc4202bf300, 0x17, ...)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/route.go:82 +0x79 fp=0xc4204fb048 sp=0xc4204fafc0 pc=0x783079
github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful.RouterJSR311.detectRoute(0xc420244480, 0x2, 0x2, 0xc420174600, 0x2, 0x2, 0xc420478167)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/jsr311.go:81 +0x66f fp=0xc4204fb928 sp=0xc4204fb048 pc=0x77e9ff
github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful.RouterJSR311.SelectRoute(0xc42000c090, 0x1, 0x1, 0xc420174600, 0x8, 0xc42044dfc0, 0x77a3b8, 0xc4204bba18)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/jsr311.go:38 +0x15c fp=0xc4204fb9c0 sp=0xc4204fb928 pc=0x77e2cc
github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful.(*RouterJSR311).SelectRoute(0x1acce80, 0xc42000c090, 0x1, 0x1, 0xc420174600, 0x10, 0x10c8d20, 0x1, 0xc420272230)
	<autogenerated>:1 +0x64 fp=0xc4204fba10 sp=0xc4204fb9c0 pc=0x7890f4
github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful.(*Container).dispatch.func4(0xc420476120, 0xc420174600, 0xc4204fbaf0, 0xc42044e0e0, 0xc420272230)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:216 +0x97 fp=0xc4204fba68 sp=0xc4204fba10 pc=0x7875b7
github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc420476120, 0x13563c0, 0xc42044e0c8, 0xc420174600)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:219 +0x15a fp=0xc4204fbbc0 sp=0xc4204fba68 pc=0x77bdaa
github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful.(*Container).(github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x13563c0, 0xc42044e0c8, 0xc420174600)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:95 +0x48 fp=0xc4204fbbf0 sp=0xc4204fbbc0 pc=0x7881e8
net/http.HandlerFunc.ServeHTTP(0xc420272420, 0x13563c0, 0xc42044e0c8, 0xc420174600)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:1947 +0x44 fp=0xc4204fbc18 sp=0xc4204fbbf0 pc=0x682214
net/http.(*ServeMux).ServeHTTP(0xc420320000, 0x13563c0, 0xc42044e0c8, 0xc420174600)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:2337 +0x130 fp=0xc4204fbc58 sp=0xc4204fbc18 pc=0x683e80
github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful.Container.ServeHTTP(0x0, 0x0, 0x0, 0xc42000c090, 0x1, 0x1, 0xc420320000, 0x0, 0x1acce80, 0x0, ...)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful/container.go:264 +0x52 fp=0xc4204fbc88 sp=0xc4204fbc58 pc=0x77c972
github.com/kubernetes/dashboard/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc420476120, 0x13563c0, 0xc42044e0c8, 0xc420174600)
	<autogenerated>:1 +0xa1 fp=0xc4204fbd38 sp=0xc4204fbc88 pc=0x788e81
net/http.(*ServeMux).ServeHTTP(0x1aadea0, 0x13563c0, 0xc42044e0c8, 0xc420174600)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:2337 +0x130 fp=0xc4204fbd78 sp=0xc4204fbd38 pc=0x683e80
net/http.serverHandler.ServeHTTP(0xc42043a5b0, 0x13563c0, 0xc42044e0c8, 0xc420174600)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:2694 +0xbc fp=0xc4204fbda8 sp=0xc4204fbd78 pc=0x684f2c
net/http.initNPNRequest.ServeHTTP(0xc4200dc000, 0xc42043a5b0, 0x13563c0, 0xc42044e0c8, 0xc420174600)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:3260 +0x9a fp=0xc4204fbf18 sp=0xc4204fbda8 pc=0x68694a
net/http.(*initNPNRequest).ServeHTTP(0xc4202a8060, 0x13563c0, 0xc42044e0c8, 0xc420174600)
	<autogenerated>:1 +0x63 fp=0xc4204fbf50 sp=0xc4204fbf18 pc=0x6a9913
net/http.(Handler).ServeHTTP-fm(0x13563c0, 0xc42044e0c8, 0xc420174600)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/h2_bundle.go:5475 +0x4d fp=0xc4204fbf80 sp=0xc4204fbf50 pc=0x6a260d
net/http.(*http2serverConn).runHandler(0xc4204ee000, 0xc42044e0c8, 0xc420174600, 0xc4204465a0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/h2_bundle.go:5760 +0x89 fp=0xc4204fbfc0 sp=0xc4204fbf80 pc=0x65dc19
runtime.goexit()
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4204fbfc8 sp=0xc4204fbfc0 pc=0x455931
created by net/http.(*http2serverConn).processHeaders
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/h2_bundle.go:5494 +0x46b

goroutine 1 [select (no cases)]:
main.main()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:171 +0x12ee

goroutine 19 [chan receive]:
github.com/kubernetes/dashboard/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1aaeaa0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/kubernetes/dashboard/vendor/github.com/golang/glog.init.0
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 35 [chan receive]:
github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents.func1()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/overwatch.go:83 +0x60
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420440f40)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420440f40, 0x0, 0x0, 0x1, 0xc4200a4300)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420440f40, 0x0, 0xc4200a4300)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0xc420440f40, 0x0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:79 +0x41
created by github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/overwatch.go:81 +0x7d

goroutine 34 [chan receive]:
github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRegistrationEvents.func1()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/overwatch.go:95 +0x60
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420440f30)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420440f30, 0x0, 0x0, 0xc4202c3a01, 0xc4200a4300)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420440f30, 0x0, 0xc4200a4300)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0xc420440f30, 0x0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:79 +0x41
created by github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRegistrationEvents
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/overwatch.go:93 +0x7d

goroutine 28 [chan receive]:
github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorSynchronizerStatus.func1()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/overwatch.go:109 +0x8e
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420260280)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420260280, 0x0, 0x0, 0xc420440f01, 0xc4200a4420)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420260280, 0x0, 0xc4200a4420)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorSynchronizerStatus
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/overwatch.go:107 +0x114

goroutine 29 [select]:
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4203e3c40, 0x45d964b800, 0x0, 0x1, 0xc4200a4540)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:145 +0x16a
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4203e3c40, 0x45d964b800, 0xc4200a4540)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubernetes/dashboard/src/app/backend/sync/poll.(*SecretPoller).Poll
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/poll/secret.go:40 +0xb3

goroutine 27 [IO wait]:
internal/poll.runtime_pollWait(0x7fada8861ff8, 0x72, 0xc420170850)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420150118, 0x72, 0xffffffffffffff00, 0x1341040, 0x1a4f480)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420150118, 0xc420270400, 0x400, 0x400)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420150100, 0xc420270400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc420150100, 0xc420270400, 0x400, 0x400, 0x8, 0x8, 0x3f3)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4200b4018, 0xc420270400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc4201acb10, 0x7fada886e518, 0xc4200b4018, 0x5, 0xc4200b4018, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc420106000, 0x1295a17, 0xc420106120, 0x20)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc420106000, 0xc42044a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/crypto/tls/conn.go:1156 +0x100
bufio.(*Reader).Read(0xc4200a25a0, 0xc4202c0118, 0x9, 0x9, 0xc4200a2898, 0xc4203e3e80, 0xc420170d10)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x133dae0, 0xc4200a25a0, 0xc4202c0118, 0x9, 0x9, 0x9, 0xc420170ce0, 0xc420170ce0, 0x4047d4)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/io/io.go:309 +0x86
io.ReadFull(0x133dae0, 0xc4200a25a0, 0xc4202c0118, 0x9, 0x9, 0xc4200a2840, 0xc420170d10, 0xc400000001)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/io/io.go:327 +0x58
github.com/kubernetes/dashboard/vendor/golang.org/x/net/http2.readFrameHeader(0xc4202c0118, 0x9, 0x9, 0x133dae0, 0xc4200a25a0, 0x0, 0xc400000000, 0x7e9dfd, 0xc420170fb0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/kubernetes/dashboard/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4202c00e0, 0xc420425650, 0x0, 0x0, 0x0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/golang.org/x/net/http2/frame.go:492 +0xa4
github.com/kubernetes/dashboard/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc420170fb0, 0x1294a68, 0xc4200577b0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/golang.org/x/net/http2/transport.go:1428 +0x8e
github.com/kubernetes/dashboard/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc4200ce1a0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/golang.org/x/net/http2/transport.go:1354 +0x76
created by github.com/kubernetes/dashboard/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/golang.org/x/net/http2/transport.go:579 +0x651

goroutine 30 [chan receive]:
github.com/kubernetes/dashboard/src/app/backend/sync.(*secretSynchronizer).Start.func1(0xc4202c2000, 0x1342480, 0xc4203e3c20)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/secret.go:73 +0x1ae
created by github.com/kubernetes/dashboard/src/app/backend/sync.(*secretSynchronizer).Start
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/sync/secret.go:67 +0x10f

goroutine 54 [IO wait]:
internal/poll.runtime_pollWait(0x7fada8861f28, 0x72, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420151a98, 0x72, 0xc42044d400, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420151a98, 0xffffffffffffff00, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420151a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc420151a80, 0xc42044d420, 0x50, 0x1132a00)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42044e820, 0x1295ad8, 0xc4204bccd0, 0xc4204bccd0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42044e820, 0x1098b80, 0x1098b80, 0xc4204bcd00)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/tcpsock.go:246 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42044e820, 0x432f64, 0xc4204bcd08, 0x452510, 0xc4204bcd48)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:3216 +0x2f
crypto/tls.(*listener).Accept(0xc4203e3820, 0x1295400, 0xc4200de000, 0x1358300, 0xc420425560)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/crypto/tls/tls.go:52 +0x37
net/http.(*Server).Serve(0xc42043a5b0, 0x134a840, 0xc4203e3820, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:2770 +0x1a5
net/http.(*Server).ServeTLS(0xc42043a5b0, 0x1356e80, 0xc42044e820, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:2839 +0x27b
net/http.(*Server).ListenAndServeTLS(0xc42043a5b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:3032 +0x11e
main.main.func1(0xc42043a5b0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:165 +0x38
created by main.main
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:165 +0x8d8

goroutine 8 [select]:
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420225fb0, 0x6fc23ac00, 0x0, 0x1, 0xc4200a4300)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:145 +0x16a
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420225fb0, 0x6fc23ac00, 0xc4200a4300)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0xc420225fb0, 0x6fc23ac00)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:79 +0x41
created by github.com/kubernetes/dashboard/src/app/backend/integration/metric.(*metricManager).EnableWithRetry
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/integration/metric/manager.go:86 +0xa9

goroutine 9 [select]:
net/http.(*http2serverConn).serve(0xc4204ee000)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/h2_bundle.go:4505 +0x5b6
net/http.(*http2Server).ServeConn(0xc4200819c0, 0x1363440, 0xc4200dc000, 0xc42009dd60)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/h2_bundle.go:4124 +0x74b
net/http.http2ConfigureServer.func1(0xc42043a5b0, 0xc4200dc000, 0x1340e20, 0xc4202a8060)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/h2_bundle.go:3962 +0x81
net/http.(*conn).serve(0xc4200de000, 0x1358300, 0xc4200da090)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:1751 +0xe9e
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/server.go:2795 +0x27b

goroutine 57 [IO wait]:
internal/poll.runtime_pollWait(0x7fada8861e58, 0x72, 0xc42016f8f0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42047e018, 0x72, 0xffffffffffffff00, 0x1341040, 0x1a4f480)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42047e018, 0xc4200f7800, 0x400, 0x400)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42047e000, 0xc4200f7800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc42047e000, 0xc4200f7800, 0x400, 0x400, 0xc4201ad3b8, 0xc4204f01c0, 0xc420074050)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4200b4038, 0xc4200f7800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc4200da180, 0x7fada886e518, 0xc4200b4038, 0x5, 0xc4200b4038, 0x62095e)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc4200dc000, 0x1295a17, 0xc4200dc120, 0x451cd0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc4200dc000, 0xc4204f0118, 0x9, 0x9, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/crypto/tls/conn.go:1156 +0x100
io.ReadAtLeast(0x7fada886e608, 0xc4200dc000, 0xc4204f0118, 0x9, 0x9, 0x9, 0x30, 0x1, 0x2)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/io/io.go:309 +0x86
io.ReadFull(0x7fada886e608, 0xc4200dc000, 0xc4204f0118, 0x9, 0x9, 0xc42008d800, 0xc42016fee0, 0xc4200a4660)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/io/io.go:327 +0x58
net/http.http2readFrameHeader(0xc4204f0118, 0x9, 0x9, 0x7fada886e608, 0xc4200dc000, 0x0, 0xc400000000, 0x2, 0x2)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/h2_bundle.go:1517 +0x7b
net/http.(*http2Framer).ReadFrame(0xc4204f00e0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/h2_bundle.go:1775 +0xa4
net/http.(*http2serverConn).readFrames(0xc4204ee000)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/h2_bundle.go:4392 +0xa9
created by net/http.(*http2serverConn).serve
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/http/h2_bundle.go:4497 +0x31a
```

**Comment by floreks** [comment]
If this happens only on a single node it is likely to be a hardware issue. I don't see anything useful in the log at a first glance.

**Comment by carsonoid** [comment]
Ok that's what I was worried about. I dug around in the code for a while trying to debug but I didn't get anywhere. Thanks for looking!
