### ISSUE TITLE
failed install on arm (Raspberry pi)

### ISSUE THREAD

**Issue by obeyler** [kubernetes/dashboard#4892]
```
kubectl logs -n kubernetes-dashboard kubernetes-dashboard-866f987876-hf5ph  

2020/02/08 15:28:53 Starting overwatch
2020/02/08 15:28:53 Using namespace: kubernetes-dashboard
2020/02/08 15:28:53 Using in-cluster config to connect to apiserver
2020/02/08 15:28:53 Using secret token for csrf signing
2020/02/08 15:28:53 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: Get https://10.96.0.1:443/api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-csrf: dial tcp 10.96.0.1:443: i/o timeout

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0x2387260)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:40 +0x300
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:65
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0x23641c0)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:494 +0xac
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0x23641c0)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:462 +0x34
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:543
main.main()
	/home/travis/build/kubernetes/dashboard/src/app/backend/dashboard.go:105 +0x1c4

```
##### Environment

```
Installation method: 
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc5/aio/deploy/recommended.yaml

Kubernetes version: 1.17.2
Dashboard version: 2.0.0-rc5
Operating system: rasbian
Node.js version ('node --version' output):
Go version ('go version' output):
```

##### Steps to reproduce
just install it
##### Observed result
```
kubectl get pods -n kubernetes-dashboard
NAME                                         READY   STATUS             RESTARTS   AGE
dashboard-metrics-scraper-7b8b58dc8b-bhbr4   1/1     Running            0          3d5h
kubernetes-dashboard-866f987876-hf5ph        0/1     CrashLoopBackOff   8          28m
```

##### Expected result
do not crash 

##### Comments
I see that the build image should works with arm but may it doesn't

**Comment by floreks** [comment]
It has nothing to do with the image. It's some kind of cluster issue. Look at the log. Request to API server times out, so it looks like there is networking issue in your cluster. Dashboard can't access critical resource and crashes.

**Comment by obeyler** [comment]
Ok so I close it Thanks for your point of view @floreks

**Comment by josephyi** [comment]
@obeyler You might have not seen the [updated documentation](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#ensure-iptables-tooling-does-not-use-the-nftables-backend) about `kubeadm` on Debian 10 (Buster). I just set up my raspberry pi cluster, and using legacy iptables + reboots seems to have resolved it. Good luck!
