### ISSUE TITLE
Continuous deployment fail

### ISSUE THREAD

**Issue by sramek5** [kubernetes/dashboard#5495]
In our infrastructure I am responsible for continuous deployment, for which we use Spinnaker ([https://spinnaker.io/](url)). 
When I deploy dashboard manually using Helm, there is no problem at all.
Our systems lead to automation, so I try to deploy dashboard using Spinnaker to all our clusters automatically.

Unfortunately, deployment always fail due `kubernetes-dashboard-csfr` secret.

### Environment
Kubernetes provider: OpenStack
Installation method: Spinnaker Continuous Delivery
Kubernetes version: v1.18.6
Dashboard version: v2.0.3
Metrics-Scraper version: v1.0.4

#### 1) - Failed Deployment
Spinnaker's `Deploy` stage fails after a few minutes due healthy check (not fully available pod).
I can check that manually and see `CrashLookBackOff`:
```
$ kubectl get all                                     
NAME                                            READY   STATUS             RESTARTS   AGE
pod/dashboard-metrics-scraper-957fd66f6-gzp7f   1/1     Running            0          5m
pod/kubernetes-dashboard-6547bd86bc-nbcbc       0/1     CrashLoopBackOff   8          5m

NAME                                  TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
service/dashboard-metrics-scraper     ClusterIP      10.110.115.69   <none>        8000/TCP        5m
service/kubernetes-dashboard          ClusterIP      10.98.105.96    <none>        443/TCP         5m

NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/dashboard-metrics-scraper   1/1     1            1           5m
deployment.apps/kubernetes-dashboard        0/1     1            0           5m

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/dashboard-metrics-scraper-957fd66f6   1         1         1       5m
replicaset.apps/kubernetes-dashboard-6547bd86bc       1         1         0       5m
```
#### 2) - Dashboard Logs
```
$ kubectl logs -n kubernetes-dashboard kubernetes-dashboard-6547bd86bc-jnhhj 
2020/09/02 11:44:07 Starting overwatch
2020/09/02 11:44:07 Using namespace: kubernetes-dashboard
2020/09/02 11:44:07 Using in-cluster config to connect to apiserver
2020/09/02 11:44:07 Using secret token for csrf signing
2020/09/02 11:44:07 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: secrets "kubernetes-dashboard-csrf" not found

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc000506720)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:41 +0x446
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:66
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc0002bb700)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:501 +0xc6
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc0002bb700)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:469 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:550
main.main()
	/home/runner/work/dashboard/dashboard/src/app/backend/dashboard.go:105 +0x20d
```
#### 3) - Spinnaker Versioning
I identified a problem, is the versioning of kubernetes object by Spinnaker ([https://spinnaker.io/reference/artifacts/in-kubernetes-v2/#versioned-kubernetes-objects](url)):
```
$ kubectl get secret -n kubernetes-dashboard 
NAME                                   TYPE                                  DATA   AGE
kubernetes-dashboard-certs-v000        Opaque                                0      10m
kubernetes-dashboard-csrf-v000         Opaque                                1      10m
kubernetes-dashboard-key-holder-v000   Opaque                                0      10m
kubernetes-dashboard-token-csczk       kubernetes.io/service-account-token   3      10m

$ kubectl get configmap -n kubernetes-dashboard
NAME                                 DATA   AGE
kubernetes-dashboard-settings-v000   0      18m
```
Here I can see that in position `DATA` is placed `0`. This means there are no data to be represented in.

#### 4) - Workaround with suffix
In other software this is not a problem, mostly is enough to specify exact secret/configmap with `-v000` suffix in deployment.yaml (and also for this purposes in rbac role.yaml for right rules).
I tried this workaround here too, but then I got:
```
$ kubectl logs kubernetes-dashboard-6547bd86bc-nbcbc 
2020/09/02 12:28:40 Starting overwatch
2020/09/02 12:28:40 Using namespace: kubernetes-dashboard
2020/09/02 12:28:40 Using in-cluster config to connect to apiserver
2020/09/02 12:28:40 Using secret token for csrf signing
2020/09/02 12:28:40 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: secrets "kubernetes-dashboard-csrf" is forbidden: User "system:serviceaccount:kubernetes-dashboard:kubernetes-dashboard" cannot get resource "secrets" in API group "" in the namespace "kubernetes-dashboard"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc000484b00)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:41 +0x446
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/csrf/manager.go:66
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc000184180)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:501 +0xc6
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc000184180)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:469 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
	/home/runner/work/dashboard/dashboard/src/app/backend/client/manager.go:550
main.main()
	/home/runner/work/dashboard/dashboard/src/app/backend/dashboard.go:105 +0x20d
```
So, now it uses "versioned" secret, but somehow the field `csrf: ""`is empty and serviceaccount has no neccessary privileges. 

##### Observed result
I changed a little bit `deplyoment.yaml` and `role.yaml` to use "versioned" secrets and configmap.
Eg. role.yaml:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
rules:
  # Allow Dashboard to get, update and delete Dashboard exclusive secrets.
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["kubernetes-dashboard-key-holder-v000", "kubernetes-dashboard-certs-v000", "kubernetes-dashboard-csrf-v000"]
    verbs: ["get", "update", "delete"]
    # Allow Dashboard to get and update 'kubernetes-dashboard-settings' config map.
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["kubernetes-dashboard-settings-v000"]
    verbs: ["get", "update"]
    # Allow Dashboard to get metrics.
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["heapster", "dashboard-metrics-scraper"]
    verbs: ["proxy"]
  - apiGroups: [""]
    resources: ["services/proxy"]
    resourceNames: ["heapster", "http:heapster:", "https:heapster:", "dashboard-metrics-scraper", "http:dashboard-metrics-scraper"]
    verbs: ["get"]
```
Secrets are still not filled with data and from this point I do not know any other workaround. It probably requires modifications on the code basis.

##### Expected result
Successful deployment using Spinnaker to all clusters.

##### Comments
I intentionally mentioned the issue here because on the Spinnaker level this workaround works on any software so far (if it is needed, sometimes we expect changing only secrets, so Spinnaker will change versioning only and kubernetes will restart pods automatically).

**Comment by maciaszczykm** [comment]
First of all, this is not a bug. Dashboard itself works fine and we were never targeting to make it work in all possible setups. There is indeed a hardcoded secret name in the code, that would need to be exported to a flag for example to allow this kind of setup. However, this could possibly be fixed on the other side if the software that you use would not add the suffixes.

**Comment by maciaszczykm** [comment]
BTW there is already an issue for that: https://github.com/kubernetes/dashboard/issues/4134.

**Comment by sramek5** [comment]
Hi, @maciaszczykm and thanks for the answer.
You are right, but sometimes we count on the versioning, because we change only secrets, not whole deployment and provisioned restarting of pods is essential.

Mentioned issue #4134 is exactly what I need. I did not noticed before, thank you.
