### ISSUE TITLE
gulp build fails

### ISSUE THREAD

**Issue by cescoferraro** [kubernetes/dashboard#610]
##### Environment
```
Dashboard version: Latest
Operating system: Ubuntu
Node.js version: v5.8.0
Go version: go version go1.6 linux/amd64
Gulp Version: [18:28:41] CLI version 3.9.1
[18:28:41] Local version 3.9.1
Babel version: 6.6.5 (babel-core 6.7.4)
```

##### Steps to reproduce
gulp build
```
cesco@desktop: ~/code/go/src/github.com/kubernetes/dashboard on master [!]
$ echo $GOPATH
/home/cesco/code/go
cesco@desktop: ~/code/go/src/github.com/kubernetes/dashboard on master [!]
$ gulp build
[18:36:08] Requiring external module babel-register
[18:36:10] Using gulpfile ~/code/go/src/github.com/kubernetes/dashboard/gulpfile.babel.js
[18:36:10] Starting 'package-backend-source'...
[18:36:10] Starting 'clean-dist'...
[18:36:10] Starting 'angular-templates'...
[18:36:10] Starting 'styles:prod'...
[18:36:10] Finished 'clean-dist' after 244 ms
[18:36:10] Starting 'fonts'...
[18:36:10] Starting 'icons'...
[18:36:10] Starting 'assets'...
[18:36:10] Finished 'assets' after 51 ms
[18:36:10] Finished 'icons' after 79 ms
[18:36:10] Finished 'fonts' after 139 ms
[18:36:10] Finished 'styles:prod' after 517 ms
[18:36:10] Finished 'angular-templates' after 528 ms
[18:36:10] Starting 'scripts:prod'...
[18:36:10] Finished 'package-backend-source' after 587 ms
[18:36:10] Starting 'backend:prod'...
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:       Current Directory: /home/cesco/code/go/src/github.com/kubernetes/dashboard
godep: [WARNING]:       $GOPATH: /home/cesco/code/go/src/github.com/kubernetes/dashboard/.tmp/backend
godep: No Godeps found (or in any parent directory)
[18:36:11] 'backend:prod' errored after 101 ms
[18:36:11] Error: Go command error, code: 1
    at Error (native)
    at ChildProcess.<anonymous> (gocommand.js:161:23)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
[18:36:18] Finished 'scripts:prod' after 7.97 s


```

**Comment by cescoferraro** [comment]
i messed something up while browsing the code.
git stash solved it
