### ISSUE TITLE
npm ci throws exception

### ISSUE THREAD

**Issue by hundanLi** [kubernetes/dashboard#6149]
##### Environment

```
Installation method: source code
Kubernetes version: none
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.2.0
Operating system: WSL 1804
Node.js version ('node --version' output): v14.17.0
Go version ('go version' output): go version go1.16.5 linux/amd64
```

##### Steps to reproduce

```
npm ci --unsafe-perm
```
##### Observed result

```
> node aio/scripts/version.mjs && command -v golangci-lint >/dev/null 2>&1 || { curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0; } && go mod download && ./aio/scripts/install-codegen.sh && ngcc

file:///opt/gopath/src/github.com/kubernetes/dashboard/aio/scripts/version.mjs:28
Object.assign(gitInfo.semver, {
       ^

TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at file:///opt/gopath/src/github.com/kubernetes/dashboard/aio/scripts/version.mjs:28:8
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```
##### Expected result

install dependencies successfully.

**Comment by floreks** [comment]
Looks like a system issue on your side since it comes from an `Object`. To be honest, WSL is not very reliable and has lots of issues. If you'd encounter such an issue on standard Linux/macOS installation then we could try investigating it.

I can only confirm that it works properly on Ubuntu 20.04.

**Comment by floreks** [comment]
No activity for a week

/close
