### ISSUE TITLE
how can i use it to develop？

### ISSUE THREAD

**Issue by luchanan** [kubernetes/dashboard#7468]
### What happened?

by get started， i install all the software. but when i npm start get.

```
PS D:\project\dashboard\modules\web> npm start

> kubernetes-dashboard@2.7.0 start
> make serve

process_begin: CreateProcess(NULL, dirname D:/project/dashboard/modules/web/Makefile, ...) failed.
Makefile:3: /../../hack/include/config.mk: No such file or directory
process_begin: CreateProcess(NULL, dirname D:/project/dashboard/modules/web/Makefile, ...) failed.
Makefile:4: /../../hack/include/build.mk: No such file or directory
make: *** No rule to make target '/../../hack/include/build.mk'.  Stop.
``` 

### What did you expect to happen?

npm start

### How can we reproduce it (as minimally and precisely as possible)?

npm start

### What browsers are you seeing the problem on?

Chrome

### Kubernetes Dashboard version

v2.7.0

### Kubernetes version

v2.7.0

**Comment by maciaszczykm** [comment]
Use `make serve` from root directory. We have just migrated to the new setup and didn't update our developer docs.

**Comment by luchanan** [comment]
> Use `make serve` from root directory. We have just migrated to the new setup and didn't update our developer docs.

when i change root directory, i got the same wrong 

```
PS D:\project\dashboard> make serve
process_begin: CreateProcess(NULL, dirname D:/project/dashboard/Makefile, ...) failed.
Makefile:3: /hack/include/config.mk: No such file or directory
Makefile:4: /hack/include/build.mk: No such file or directory
Makefile:6: /hack/include/config.mk: No such file or directory
Makefile:7: /hack/include/config.mk: No such file or directory
make: *** No rule to make target '/hack/include/config.mk'.  Stop.
```

**Comment by luchanan** [comment]
i try to download 2.7 tag, then yarn

```
success Saved lockfile.
$ make ensure-version && ngcc
process_begin: CreateProcess(NULL, dirname D:/project/dashboard-2.7.0/dashboard-2.7.0/Makefile, ...) failed.
node ./aio/scripts/version.mjs
file:///D:/project/dashboard-2.7.0/dashboard-2.7.0/aio/scripts/version.mjs:28
Object.assign(gitInfo.semver, {
       ^

TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at file:///D:/project/dashboard-2.7.0/dashboard-2.7.0/aio/scripts/version.mjs:28:8
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
Makefile:43: recipe for target 'ensure-version' failed
make: *** [ensure-version] Error 1
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by floreks** [comment]
What OS are you using? If it's windows then it will not work. We aim to support linux/macos for development. You can also try using linux for windows.

**Comment by maciaszczykm** [comment]
Yeah, I have also noticed Windows paths. It will not work.

**Comment by luchanan** [comment]
window10, i install Ubuntu in vmware. but got
root@iv-virtual-machine:/home/iv/project/dashboard-2.7.0# yarn start
yarn run v1.22.19
$ concurrently "SIDECAR_HOST=$npm_config_sidecar_host make watch-backend" "npm run start:frontend --bind_address=$npm_config_bind_address --port=$npm_config_port"
[0] curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /home/iv/go/bin
[1] 
[1] > kubernetes-dashboard@2.7.0 start:frontend
[1] > make ensure-version && ng serve --proxy-config aio/proxy.conf.json --host $npm_config_bind_address --port $npm_config_port
[1] 
[1] node ./aio/scripts/version.mjs
[1] file:///home/iv/project/dashboard-2.7.0/aio/scripts/version.mjs:28
[1] Object.assign(gitInfo.semver, {
[1]        ^
[1] 
[1] TypeError: Cannot convert undefined or null to object
[1]     at Function.assign (<anonymous>)
[1]     at file:///home/iv/project/dashboard-2.7.0/aio/scripts/version.mjs:28:8
[1]     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
[1]     at async Promise.all (index 0)
[1]     at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
[1]     at async loadESM (node:internal/process/esm_loader:91:5)
[1]     at async handleMainPromise (node:internal/modules/run_main:65:12)
[1] make: *** [Makefile:43：ensure-version] 错误 1
[1] npm run start:frontend --bind_address=127.0.0.1 --port=8080 exited with code 2
[0] curl: (56) OpenSSL SSL_read: 连接被对方重设, errno 104
[0] air
[0] /bin/bash: 行 1: air：未找到命令
[0] make: *** [Makefile:109：watch-backend] 错误 127
[0] SIDECAR_HOST=http://localhost:8000 make watch-backend exited with code 2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by floreks** [comment]
You probably don't have all the required dependencies installed. We still need to improve the checks for them. You definitely need node 16.15+/git/go/make and some other things I don't remember right now.

**Comment by maciaszczykm** [comment]
Yes, it seems to fail at `node ./aio/scripts/version.mjs` which is quite uncommon error. Check if your repository is valid and if you are able to run `git status` for example.

**Comment by floreks** [comment]
Please fetch the latest changes from the master. It should now have been fixed. The order of targets was incorrect and the version script was running before dependencies were installed.

/close
