### ISSUE TITLE
kubernetes-dashboard crashes in AWS EKS

### ISSUE THREAD

**Issue by regnaio** [kubernetes/dashboard#7655]
### What happened?

```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml

---

kubectl logs -n kubernetes-dashboard kubernetes-dashboard-5896b465dd-826zh

2023/03/11 19:15:58 Starting overwatch
2023/03/11 19:15:58 Using kubeconfig file: /root/.kube/config
2023/03/11 19:15:58 Using namespace: kubernetes-dashboard
2023/03/11 19:15:58 Skipping in-cluster config
2023/03/11 19:15:58 Using random key for csrf signing
2023/03/11 19:15:58 Successful initial request to the apiserver, version: v1.25.6-eks-48e63af
2023/03/11 19:15:58 Generating JWE encryption key
2023/03/11 19:15:58 New synchronizer has been registered: kubernetes-dashboard-key-holder-kubernetes-dashboard. Starting
2023/03/11 19:15:58 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kubernetes-dashboard
2023/03/11 19:15:58 Synchronizer kubernetes-dashboard-key-holder-kubernetes-dashboard exited with error: unexpected object: &Secret{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Data:map[string][]byte{},Type:,StringData:map[string]string{},Immutable:nil,}
2023/03/11 19:15:59 Storing encryption key in a secret
panic: secrets is forbidden: User "system:node:ip-172-31-29-245.us-west-1.compute.internal" cannot create resource "secrets" in API group "" in the namespace "kubernetes-dashboard": can only read resources of this type

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).init(0xc0002f13e0)
        /home/runner/work/dashboard/dashboard/src/app/backend/auth/jwe/keyholder.go:138 +0x26a
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.NewRSAKeyHolder(...)
        /home/runner/work/dashboard/dashboard/src/app/backend/auth/jwe/keyholder.go:177
main.initAuthManager({0x1c41f00, 0xc00003e900})
        /home/runner/work/dashboard/dashboard/src/app/backend/dashboard.go:205 +0x127
main.main()
        /home/runner/work/dashboard/dashboard/src/app/backend/dashboard.go:105 +0x2dd
```

### What did you expect to happen?

Expected `kubernetes-dashboard` to work out of the box in AWS EKS after `kubectl apply`. It works fine in DigitalOcean DOKS and GCP GKE

### How can we reproduce it (as minimally and precisely as possible)?

Create an EKS cluster on AWS with a single Node Group with a single Node

Then run:
```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
```

Observe that `kubernetes-dashboard` pod has Status: `CrashLoopBackOff`

Note: This works fine in DigitalOcean DOKS and GCP GKE

I always made sure that the Secret `kubernetes-dashboard-key-holder` exists before the Pod runs

### Kubernetes Dashboard version

v2.7.0

### Kubernetes version

1.25

**Comment by floreks** [comment]
I see that you are using some custom configuration since Dashboard is using kubeconfig file to start. It should not do that.

> Using kubeconfig file: /root/.kube/config
