### ISSUE TITLE
Synchronizer kubernetes-dashboard-key-holder exited with error: unexpected object -> watch ended with timeout -> panic crash

### ISSUE THREAD

**Issue by Basssiiie** [kubernetes/dashboard#7904]
### What happened?

I've got Kubernetes Dashboard running in my cluster, but it crashes every handful of hours with the following errors:
```
2023/06/16 08:25:09 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: unexpected object: &Secret{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Data:map[string][]byte{},Type:,StringData:map[string]string{},Immutable:nil,}
```
Followed by about 10 attempts to re-watch the key-holder secret:
```
2023/06/16 08:25:11 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:11 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:11 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
```
And then finally killing itself in panic mode:
```
E0616 08:25:41.582294       1 runtime.go:77] Observed a panic: synchronizer kubernetes-dashboard-key-holder-admin restart limit execeeded. Restarting pod.
goroutine 12 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x16c68e0?, 0xc0001aa340})
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x203000?})
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:49 +0x75
        /opt/hostedtoolcache/go/1.19.0/x64/src/runtime/panic.go:884 +0x212
github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents.func1()
        /home/runner/work/dashboard/dashboard/src/app/backend/sync/overwatch.go:92 +0x159
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000024f08?)
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x1c23980, 0xc0003ec0f0}, 0x1, 0xc0000d4a80)
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x0, 0x0, 0x0?, 0x0?)
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:92
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:83 +0x28
created by github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents
        /home/runner/work/dashboard/dashboard/src/app/backend/sync/overwatch.go:88 +0x98
panic: synchronizer kubernetes-dashboard-key-holder-admin restart limit execeeded. Restarting pod. [recovered]
        panic: synchronizer kubernetes-dashboard-key-holder-admin restart limit execeeded. Restarting pod.
```
The pod list currently looks like this, with about 10 restarts in the last 29 hours:
```
$ kubectl get pod -n admin
NAME                                                     READY   STATUS    RESTARTS         AGE
admin-monitoring-kubernetes-dashboard-69c9477cc9-w6f94   1/1     Running   10 (6h46m ago)   29h
```

Full uncut logs:

<details>
<summary>Click here</summary>

```
$ kubectl logs admin-monitoring-kubernetes-dashboard-69c9477cc9-w6f94 -n admin --previous
2023/06/16 07:54:59 Starting overwatch
2023/06/16 07:54:59 Using namespace: admin
2023/06/16 07:54:59 Using in-cluster config to connect to apiserver
2023/06/16 07:54:59 Using secret token for csrf signing
2023/06/16 07:54:59 Initializing csrf token from kubernetes-dashboard-csrf secret
2023/06/16 07:54:59 Successful initial request to the apiserver, version: v1.23.15
2023/06/16 07:54:59 Generating JWE encryption key
2023/06/16 07:54:59 New synchronizer has been registered: kubernetes-dashboard-key-holder-admin. Starting
2023/06/16 07:54:59 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 07:54:59 Initializing JWE encryption key from synchronized object
2023/06/16 07:54:59 no metrics provider selected, will not check metrics.
2023/06/16 07:54:59 Auto-generating certificates
2023/06/16 07:54:59 Successfully created certificates
2023/06/16 07:54:59 Serving securely on HTTPS port: 8443
2023/06/16 08:25:09 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: unexpected object: &Secret{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Data:map[string][]byte{},Type:,StringData:map[string]string{},Immutable:nil,}
2023/06/16 08:25:11 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:11 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:11 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:13 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:13 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:13 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:15 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:15 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:15 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:17 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:17 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:17 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:19 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:19 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:19 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:21 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:21 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:21 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:23 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:23 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:23 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:25 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:25 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:25 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:27 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:27 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:27 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:29 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:29 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:29 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:31 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:31 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:31 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:33 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:33 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:33 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:35 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:35 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:35 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:37 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:37 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:37 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
2023/06/16 08:25:39 Restarting synchronizer: kubernetes-dashboard-key-holder-admin.
2023/06/16 08:25:39 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace admin
2023/06/16 08:25:39 Synchronizer kubernetes-dashboard-key-holder-admin exited with error: kubernetes-dashboard-key-holder-admin watch ended with timeout
E0616 08:25:41.582294       1 runtime.go:77] Observed a panic: synchronizer kubernetes-dashboard-key-holder-admin restart limit execeeded. Restarting pod.
goroutine 12 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x16c68e0?, 0xc0001aa340})
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x203000?})
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:49 +0x75
        /opt/hostedtoolcache/go/1.19.0/x64/src/runtime/panic.go:884 +0x212
github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents.func1()
        /home/runner/work/dashboard/dashboard/src/app/backend/sync/overwatch.go:92 +0x159
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000024f08?)
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x1c23980, 0xc0003ec0f0}, 0x1, 0xc0000d4a80)
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x0, 0x0, 0x0?, 0x0?)
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:92
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:83 +0x28
created by github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents
        /home/runner/work/dashboard/dashboard/src/app/backend/sync/overwatch.go:88 +0x98
panic: synchronizer kubernetes-dashboard-key-holder-admin restart limit execeeded. Restarting pod. [recovered]
        panic: synchronizer kubernetes-dashboard-key-holder-admin restart limit execeeded. Restarting pod.

goroutine 12 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x203000?})
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x16c68e0, 0xc0001aa340})
        /opt/hostedtoolcache/go/1.19.0/x64/src/runtime/panic.go:884 +0x212
github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents.func1()
        /home/runner/work/dashboard/dashboard/src/app/backend/sync/overwatch.go:92 +0x159
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000024f08?)
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x1c23980, 0xc0003ec0f0}, 0x1, 0xc0000d4a80)
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x0, 0x0, 0x0?, 0x0?)
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:92
        /home/runner/go/bin/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:83 +0x28
created by github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents
        /home/runner/work/dashboard/dashboard/src/app/backend/sync/overwatch.go:88 +0x98
```

</details>

### What did you expect to happen?

I expect Kubernetes Dashboard to run for a lot longer without crashing.

### How can we reproduce it (as minimally and precisely as possible)?

I've got Kubernetes Dashboard deployed via a Helm template.

Chart.yaml:
```yaml
apiVersion: v2
name: admin-monitoring
type: application
version: 1.0.0
dependencies:
- name: kubernetes-dashboard
  version: "^6.0.0"
  repository: https://kubernetes.github.io/dashboard/
```
And the following values.yaml:
```yaml
kubernetes-dashboard:
  extraArgs:
    - --enable-skip-login
  ingress:
    enabled: true
    tls: {TAKEN OUT}
    hosts: {TAKEN OUT}
    className: nginx
    paths:
    - "/kubernetes(/|$)(.*)"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/configuration-snippet: |
        if ($uri = "/kubernetes") { return 302 /kubernetes/; }
  settings:
    clusterName: "Test"
    defaultNamespace: "env-a"
    namespaceFallbackList: ["env-a", "env-b"]
    itemsPerPage: 20
    labelsLimit: 0
    logsAutoRefreshTimeInterval: 10
    resourceAutoRefreshTimeInterval: 10
```
The following roles and rolebindings are attached:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-monitoring-viewer-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "pods/log", "deployments", "events", "replicasets"]
  verbs: ["get", "watch", "list"]


{{- range (index .Values "kubernetes-dashboard" "settings" "namespaceFallbackList") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-monitoring-viewer-role-binding-{{ . }}
  namespace: {{ . }}
subjects:
- kind: ServiceAccount
  name: admin-monitoring-kubernetes-dashboard
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: admin-monitoring-viewer-role
  apiGroup: rbac.authorization.k8s.io
{{- end }} 
```

This Helm chart called `admin-monitoring` and is installed via:
```
helm upgrade --install admin-monitoring admin-monitoring --namespace admin --create-namespace --dependency-update --debug 
```

### Anything else we need to know?

The dashboard is running in an Azure Kubernetes environment. I'm not sure if it's relevant, but we do use [Microsoft's Azure Secrets Store Provider](https://github.com/Azure/secrets-store-csi-driver-provider-azure) to synchronize various selected secrets (like certificates) between AKS and Azure Keyvault. We do not sync anything for the Kubernetes Dashboard itself though apart from an TLS certificate into the same namespace.

### Kubernetes Dashboard version

Dashboard v2.7.0+0.g42deb6b32

### Kubernetes version

Client Version: v1.25.9, Kustomize Version: v4.5.7, Server Version: v1.23.15

**Comment by floreks** [comment]
Most of the time it is related to connectivity issues between Dashboard and API server. Isn't there something that could potentially be blocking/dropping requests from time to time? Maybe API server becomes unresponsive from time to time.

Another option is that the `kubernetes-dashboard-key-holder` secret is being altered by some external tool.

I will have to add some more logs in this case as I see that the real error is not being logged right now, so I can only speculate on the real reason behind this.

**Comment by Basssiiie** [comment]
@floreks Thank you for your reply. I am not aware of any unresponsiveness from the API server or any tool altering the secret. Would you have some suggestions how I can check whether one of these is the case?

Also if there is anything further I can do to give you some more information regarding the issue, please let me know. 🙂

**Comment by floreks** [comment]
Unfortunately, we have to first update the code to add more logging and be able to see the real error.

**Comment by zhonghuali** [comment]
more questions, did the kubernetes-dashboard-key-holder-kubernetes-dashboard watch have to connect to internet ,which is the url?

**Comment by floreks** [comment]
Dashboard should work perfectly fine without access to the internet as all dependencies are embedded into the app. It does not need access to the internet, only API server.

**Comment by maciaszczykm** [comment]
Dashboard no longer uses these secrets. Please check the upcoming release once it will be out.
